// packages/svelte/src/ui/breadcrumb/breadcrumb-item.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "../../lib/utils.js";
	import type { HTMLLiAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLLiAttributes> = $props();
</script>

<li
	bind:this={ref}
	data-slot="breadcrumb-item"
	class={cn("hp:gap-1 hp:inline-flex hp:items-center", className)}
	{...restProps}
>
	{@render children?.()}
</li>

// packages/vue/src/ui/breadcrumb/BreadcrumbItem.vue
<script lang="ts" setup>
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <li
    data-slot="breadcrumb-item"
    :class="cn('hp:inline-flex hp:items-center hp:gap-1.5', props.class)"
  >
    <slot />
  </li>
</template>
