// packages/svelte/src/ui/breadcrumb/breadcrumb-ellipsis.svelte
<script lang="ts">
	import MoreHorizontalIcon from '@lucide/svelte/icons/more-horizontal';
	import { cn, type WithElementRef, type WithoutChildren } from "../../lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: WithoutChildren<WithElementRef<HTMLAttributes<HTMLSpanElement>>> = $props();
</script>

<span
	bind:this={ref}
	data-slot="breadcrumb-ellipsis"
	role="presentation"
	aria-hidden="true"
	class={cn("hp:size-5 hp:[&>svg]:size-4 hp:flex hp:items-center hp:justify-center", className)}
	{...restProps}
>
	<MoreHorizontalIcon  />
	<span class="hp:sr-only">More</span>
</span>

// packages/vue/src/ui/breadcrumb/BreadcrumbEllipsis.vue
<script lang="ts" setup>
import type { HTMLAttributes } from "vue"
import { DotsHorizontalIcon } from '@radix-icons/vue'
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <span
    data-slot="breadcrumb-ellipsis"
    role="presentation"
    aria-hidden="true"
    :class="cn('hp:flex hp:size-9 hp:items-center hp:justify-center', props.class)"
  >
    <slot>
      <DotsHorizontalIcon class="hp:size-4" />
    </slot>
    <span class="hp:sr-only">More</span>
  </span>
</template>
