// apps/example-sveltekit/src/routes/admin/profile/+page.svelte
<!-- @holo-panels-managed sha256:269732d8d74c81fa147994457f0471e84efd0eb3e0b6e69cae3618d1ef9c0ac5 -->
<script lang="ts">
  import '@holo-js/panels-svelte/style.css'
  import { PanelProfilePage } from '@holo-js/panels-sveltekit'
</script>

<PanelProfilePage brandName={"Holo Panels"} panelId="admin" simplePageMaxContentWidth="lg" theme="system" appearance={{"colors":{"primary":"#7c3aed"},"density":"comfortable","fontFamily":null,"monoFontFamily":null,"serifFontFamily":null,"tokens":{}}} />

// apps/example-next/app/admin/profile/page.tsx
// @holo-panels-managed sha256:873e6e8fe722fe4a3bfe38196e3c8b57700aa90a0210a7ef4063fe32e028b03f
'use client'

import '@holo-js/panels-react/style.css'
import { NextPanelProfilePage } from '@holo-js/panels-next/client'

export default function AuthPage() {
  return <NextPanelProfilePage brandName={"Holo Panels Admin"} panelId="admin" simplePageMaxContentWidth="lg" theme="system" appearance={{"colors":{"primary":"#7c3aed"},"density":"comfortable","fontFamily":null,"monoFontFamily":null,"serifFontFamily":null,"tokens":{}}} />
}
