// packages/svelte/src/ui/card/card-header.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "../../lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();
</script>

<div
	bind:this={ref}
	data-slot="card-header"
	class={cn(
		"hp:gap-1 hp:rounded-t-xl hp:px-(--card-spacing) hp:[.border-b]:pb-(--card-spacing) hp:group/card-header hp:@container/card-header hp:grid hp:auto-rows-min hp:items-start hp:has-data-[slot=card-action]:grid-cols-[1fr_auto] hp:has-data-[slot=card-description]:grid-rows-[auto_auto]",
		className
	)}
	{...restProps}
>
	{@render children?.()}
</div>

// packages/vue/src/ui/card/CardHeader.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <div
    data-slot="card-header"
    :class="cn('hp:@container/card-header hp:grid hp:auto-rows-min hp:grid-rows-[auto_auto] hp:items-start hp:gap-1.5 hp:px-6 hp:has-data-[slot=card-action]:grid-cols-[1fr_auto] hp:[.border-b]:pb-6', props.class)"
  >
    <slot />
  </div>
</template>
