// packages/sveltekit/src/MultiFactorPage.svelte
<script lang="ts">
  import { executePanelAuthRequest, panelContentWidthValue, panelThemeStyleAttribute, type PanelClientAuthOperation } from '@holo-js/panels-svelte'
  import { onMount } from 'svelte'
  import Button from './Button.svelte'
  import Icon from './Icon.svelte'
  import Input from './Input.svelte'

  interface Props {
    brandName: string
    panelId: string
    simplePageMaxContentWidth?: string
    theme?: 'dark' | 'light' | 'system'
    themeColors?: Readonly<Record<string, string>>
  }

  let { brandName, panelId, simplePageMaxContentWidth, theme = 'system', themeColors }: Props = $props()
  let enabled = $state(false)
  let manualKey = $state('')
  let recoveryCodes = $state<readonly string[]>([])
  let code = $state('')
  let method = $state<'recovery' | 'totp'>('totp')
  let error = $state('')

  function cookie(name: string): string {
    const entry = document.cookie.split(';').map(value => value.trim()).find(value => value.startsWith(`${name}=`))
    return entry ? decodeURIComponent(entry.slice(name.length + 1)) : ''
  }

  const request = (operation: PanelClientAuthOperation, payload: Readonly<Record<string, unknown>> = {}) => executePanelAuthRequest({ csrfToken: cookie('XSRF-TOKEN'), operation, panelId, payload })

  onMount(() => {
    void request('mfa-status').then((result) => {
      if (result.ok && typeof result.data === 'object' && result.data !== null && 'enabled' in result.data) enabled = result.data.enabled === true
    })
  })

  async function begin(): Promise<void> {
    const result = await request('mfa-enrollment-begin')
    if (!result.ok || typeof result.data !== 'object' || result.data === null || !('manualKey' in result.data)) error = 'Multi-factor enrollment could not be started.'
    else manualKey = String(result.data.manualKey)
  }

  async function confirm(event: SubmitEvent): Promise<void> {
    event.preventDefault()
    if (!(event.currentTarget instanceof HTMLFormElement)) return
    const values = new FormData(event.currentTarget)
    const result = await request('mfa-enrollment-confirm', { code: String(values.get('code') ?? '') })
    if (!result.ok || typeof result.data !== 'object' || result.data === null || !('recoveryCodes' in result.data) || !Array.isArray(result.data.recoveryCodes)) error = 'Multi-factor enrollment could not be confirmed.'
    else {
      recoveryCodes = result.data.recoveryCodes.map(String)
      enabled = true
    }
  }

  async function protectedAction(event: SubmitEvent, operation: 'mfa-disable' | 'mfa-recovery-codes-regenerate'): Promise<void> {
    event.preventDefault()
    if (!(event.currentTarget instanceof HTMLFormElement)) return
    const values = new FormData(event.currentTarget)
    const result = await request(operation, { code: String(values.get('code') ?? ''), method: values.get('method') === 'recovery' ? 'recovery' : 'totp' })
    if (!result.ok) error = 'The multi-factor request could not be completed.'
    else if (operation === 'mfa-disable') {
      enabled = false
      manualKey = ''
      recoveryCodes = []
    } else if (typeof result.data === 'object' && result.data !== null && 'recoveryCodes' in result.data && Array.isArray(result.data.recoveryCodes)) recoveryCodes = result.data.recoveryCodes.map(String)
  }
</script>

<main class="hp-auth-page" data-holo-panel data-theme={theme} style={`${panelThemeStyleAttribute({ colors: themeColors })}${simplePageMaxContentWidth ? `--hp-auth-max-width:${panelContentWidthValue(simplePageMaxContentWidth)};` : ''}`}>
  <section class="hp-auth-card" data-slot="card">
    <div data-slot="card-header"><span class="hp-auth-brand-mark"><Icon name="key" /></span><div><p>{brandName}</p><h1>Multi-factor authentication</h1><span>MFA is {enabled ? 'enabled' : 'disabled'}.</span></div></div>
    <div data-slot="card-content">
      {#if !enabled && !manualKey}<Button class="hp-button hp-button-primary" onclick={() => void begin()}>Begin enrollment</Button>{/if}
      {#if manualKey}<section><p>Manual key: <code>{manualKey}</code></p><form onsubmit={confirm}><div class="hp-auth-field"><label data-slot="label" for={`${panelId}-confirm-code`}>Authentication code</label><Input id={`${panelId}-confirm-code`} name="code" bind:value={code} required /></div><Button class="hp-button hp-button-primary" type="submit">Confirm enrollment</Button></form></section>{/if}
      {#if recoveryCodes.length}<section aria-label="Recovery codes"><h2>Recovery codes</h2><ul>{#each recoveryCodes as recoveryCode}<li><code>{recoveryCode}</code></li>{/each}</ul></section>{/if}
      {#if enabled}<form onsubmit={(event) => protectedAction(event, 'mfa-recovery-codes-regenerate')}><div class="hp-auth-field"><label data-slot="label" for={`${panelId}-regenerate-method`}>Verification method</label><select data-slot="native-select" id={`${panelId}-regenerate-method`} name="method" bind:value={method}><option value="totp">Authenticator code</option><option value="recovery">Recovery code</option></select></div><div class="hp-auth-field"><label data-slot="label" for={`${panelId}-regenerate-code`}>Authentication code</label><Input id={`${panelId}-regenerate-code`} name="code" bind:value={code} required /></div><Button class="hp-button" type="submit">Regenerate recovery codes</Button></form>{/if}
      {#if enabled}<form onsubmit={(event) => protectedAction(event, 'mfa-disable')}><div class="hp-auth-field"><label data-slot="label" for={`${panelId}-disable-method`}>Verification method</label><select data-slot="native-select" id={`${panelId}-disable-method`} name="method" bind:value={method}><option value="totp">Authenticator code</option><option value="recovery">Recovery code</option></select></div><div class="hp-auth-field"><label data-slot="label" for={`${panelId}-disable-code`}>Authentication code</label><Input id={`${panelId}-disable-code`} name="code" bind:value={code} required /></div><Button class="hp-button hp-button-destructive" type="submit">Disable multi-factor authentication</Button></form>{/if}
      {#if error}<p class="hp-auth-error" role="alert">{error}</p>{/if}
    </div>
  </section>
</main>

// packages/next/src/multi-factor-page.tsx
'use client'

import { executePanelAuthRequest, panelContentWidthValue, panelThemeVariables } from '@holo-js/panels-react'
import { useEffect, useState, type CSSProperties, type FormEvent } from 'react'
import { ShadcnButton, ShadcnCard, ShadcnCardContent, ShadcnCardHeader, ShadcnIcon, ShadcnInput, ShadcnLabel, ShadcnSelect } from './internal-ui'

export interface NextPanelMultiFactorPageProps {
  readonly brandName: string
  readonly panelId: string
  readonly simplePageMaxContentWidth?: string
  readonly theme?: 'dark' | 'light' | 'system'
  readonly themeColors?: Readonly<Record<string, string>>
}

function cookie(name: string): string {
  const entry = document.cookie.split(';').map(value => value.trim()).find(value => value.startsWith(`${name}=`))
  return entry ? decodeURIComponent(entry.slice(name.length + 1)) : ''
}

export function NextPanelMultiFactorPage({ brandName, panelId, simplePageMaxContentWidth, theme = 'system', themeColors }: NextPanelMultiFactorPageProps) {
  const [enabled, setEnabled] = useState(false)
  const [manualKey, setManualKey] = useState('')
  const [recoveryCodes, setRecoveryCodes] = useState<readonly string[]>([])
  const [error, setError] = useState('')
  const style = { ...panelThemeVariables({ colors: themeColors }), ...(simplePageMaxContentWidth ? { '--hp-auth-max-width': panelContentWidthValue(simplePageMaxContentWidth) } : {}) } as CSSProperties
  const request = (operation: Parameters<typeof executePanelAuthRequest>[0]['operation'], payload: Readonly<Record<string, unknown>> = {}) => executePanelAuthRequest({ csrfToken: cookie('XSRF-TOKEN'), operation, panelId, payload })

  useEffect(() => {
    void request('mfa-status').then((result) => {
      if (result.ok && typeof result.data === 'object' && result.data !== null && 'enabled' in result.data) setEnabled(result.data.enabled === true)
    })
  }, [])

  async function begin(): Promise<void> {
    const result = await request('mfa-enrollment-begin')
    if (!result.ok || typeof result.data !== 'object' || result.data === null || !('manualKey' in result.data)) return setError('Multi-factor enrollment could not be started.')
    setManualKey(String(result.data.manualKey))
  }

  async function confirm(event: FormEvent<HTMLFormElement>): Promise<void> {
    event.preventDefault()
    const result = await request('mfa-enrollment-confirm', { code: String(new FormData(event.currentTarget).get('code') ?? '') })
    if (!result.ok || typeof result.data !== 'object' || result.data === null || !('recoveryCodes' in result.data) || !Array.isArray(result.data.recoveryCodes)) return setError('Multi-factor enrollment could not be confirmed.')
    setRecoveryCodes(result.data.recoveryCodes.map(String))
    setEnabled(true)
  }

  async function protectedAction(event: FormEvent<HTMLFormElement>, operation: 'mfa-disable' | 'mfa-recovery-codes-regenerate'): Promise<void> {
    event.preventDefault()
    const values = new FormData(event.currentTarget)
    const result = await request(operation, { code: String(values.get('code') ?? ''), method: values.get('method') === 'recovery' ? 'recovery' : 'totp' })
    if (!result.ok) return setError('The multi-factor request could not be completed.')
    if (operation === 'mfa-disable') {
      setEnabled(false)
      setManualKey('')
      setRecoveryCodes([])
    } else if (typeof result.data === 'object' && result.data !== null && 'recoveryCodes' in result.data && Array.isArray(result.data.recoveryCodes)) {
      setRecoveryCodes(result.data.recoveryCodes.map(String))
    }
  }

  return <main className="hp-auth-page" data-holo-panel data-theme={theme} style={style}><ShadcnCard className="hp-auth-card"><ShadcnCardHeader><span className="hp-auth-brand-mark"><ShadcnIcon name="key" /></span><div><p>{brandName}</p><h1>Multi-factor authentication</h1><span>MFA is {enabled ? 'enabled' : 'disabled'}.</span></div></ShadcnCardHeader><ShadcnCardContent>
    {!enabled && !manualKey ? <ShadcnButton className="hp-button hp-button-primary" onClick={() => void begin()}>Begin enrollment</ShadcnButton> : null}
    {manualKey ? <><p>Manual key: <code>{manualKey}</code></p><form onSubmit={confirm}><div className="hp-auth-field"><ShadcnLabel htmlFor={`${panelId}-confirm-code`}>Authentication code</ShadcnLabel><ShadcnInput autoComplete="one-time-code" id={`${panelId}-confirm-code`} name="code" required /></div><ShadcnButton className="hp-button hp-button-primary" type="submit">Confirm enrollment</ShadcnButton></form></> : null}
    {recoveryCodes.length ? <section aria-label="Recovery codes"><h2>Recovery codes</h2><ul>{recoveryCodes.map(code => <li key={code}><code>{code}</code></li>)}</ul></section> : null}
    {enabled ? <form onSubmit={event => void protectedAction(event, 'mfa-recovery-codes-regenerate')}><div className="hp-auth-field"><ShadcnLabel htmlFor={`${panelId}-regenerate-method`}>Verification method</ShadcnLabel><ShadcnSelect id={`${panelId}-regenerate-method`} name="method"><option value="totp">Authenticator code</option><option value="recovery">Recovery code</option></ShadcnSelect></div><div className="hp-auth-field"><ShadcnLabel htmlFor={`${panelId}-regenerate-code`}>Code</ShadcnLabel><ShadcnInput id={`${panelId}-regenerate-code`} name="code" required /></div><ShadcnButton className="hp-button" type="submit">Regenerate recovery codes</ShadcnButton></form> : null}
    {enabled ? <form onSubmit={event => void protectedAction(event, 'mfa-disable')}><div className="hp-auth-field"><ShadcnLabel htmlFor={`${panelId}-disable-method`}>Verification method</ShadcnLabel><ShadcnSelect id={`${panelId}-disable-method`} name="method"><option value="totp">Authenticator code</option><option value="recovery">Recovery code</option></ShadcnSelect></div><div className="hp-auth-field"><ShadcnLabel htmlFor={`${panelId}-disable-code`}>Code</ShadcnLabel><ShadcnInput id={`${panelId}-disable-code`} name="code" required /></div><ShadcnButton className="hp-button hp-button-destructive" type="submit">Disable multi-factor authentication</ShadcnButton></form> : null}
    {error ? <p className="hp-auth-error" role="alert">{error}</p> : null}
  </ShadcnCardContent></ShadcnCard></main>
}
