// packages/vue/src/ui/breadcrumb/BreadcrumbList.vue
<script lang="ts" setup>
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <ol
    data-slot="breadcrumb-list"
    :class="cn('hp:text-muted-foreground hp:flex hp:flex-wrap hp:items-center hp:gap-1.5 hp:text-sm hp:break-words hp:sm:gap-2.5', props.class)"
  >
    <slot />
  </ol>
</template>

// packages/svelte/src/ui/breadcrumb/breadcrumb-list.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "../../lib/utils.js";
	import type { HTMLOlAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLOlAttributes> = $props();
</script>

<ol
	bind:this={ref}
	data-slot="breadcrumb-list"
	class={cn("hp:gap-1.5 hp:text-sm hp:text-muted-foreground hp:flex hp:flex-wrap hp:items-center hp:wrap-break-word", className)}
	{...restProps}
>
	{@render children?.()}
</ol>
