// packages/svelte/src/ui/alert-dialog/alert-dialog-description.svelte
<script lang="ts">
	import { AlertDialog as AlertDialogPrimitive } from "bits-ui";
	import { cn } from "../../lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: AlertDialogPrimitive.DescriptionProps = $props();
</script>

<AlertDialogPrimitive.Description
	bind:ref
	data-slot="alert-dialog-description"
	class={cn("hp:text-sm hp:text-balance hp:text-muted-foreground hp:md:text-pretty hp:*:[a]:underline hp:*:[a]:underline-offset-3 hp:*:[a]:hover:text-foreground", className)}
	{...restProps}
/>

// packages/vue/src/ui/alert-dialog/AlertDialogDescription.vue
<script setup lang="ts">
import type { AlertDialogDescriptionProps } from "reka-ui"
import type { HTMLAttributes } from "vue"
import { reactiveOmit } from "@vueuse/core"
import {
  AlertDialogDescription,
} from "reka-ui"
import { cn } from "@/lib/utils"

const props = defineProps<AlertDialogDescriptionProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = reactiveOmit(props, "class")
</script>

<template>
  <AlertDialogDescription
    data-slot="alert-dialog-description"
    v-bind="delegatedProps"
    :class="cn('hp:text-muted-foreground hp:text-sm', props.class)"
  >
    <slot />
  </AlertDialogDescription>
</template>
