// packages/svelte/src/ui/sidebar/sidebar-group.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "../../lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLElement>> = $props();
</script>

<div
	bind:this={ref}
	data-slot="sidebar-group"
	data-sidebar="group"
	class={cn("hp:p-2 hp:relative hp:flex hp:w-full hp:min-w-0 hp:flex-col", className)}
	{...restProps}
>
	{@render children?.()}
</div>

// packages/vue/src/ui/sidebar/SidebarGroup.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <div
    data-slot="sidebar-group"
    data-sidebar="group"
    :class="cn('hp:relative hp:flex hp:w-full hp:min-w-0 hp:flex-col hp:p-2', props.class)"
  >
    <slot />
  </div>
</template>
