// packages/svelte/src/ui/sidebar/sidebar-trigger.svelte
<script lang="ts">
	import PanelLeftIcon from '@lucide/svelte/icons/panel-left';
	import { Button } from "../button/index.js";
	import { cn } from "../../lib/utils.js";
	import { useSidebar } from "./context.svelte.js";
	import type { ComponentProps } from "svelte";

	let {
		ref = $bindable(null),
		class: className,
		onclick,
		label = "Toggle Sidebar",
		...restProps
	}: ComponentProps<typeof Button> & {
		onclick?: (e: MouseEvent) => void;
		label?: string;
	} = $props();

	const sidebar = useSidebar();
	let previousOpenMobile = false;

	$effect(() => {
		const openMobile = sidebar.openMobile;
		if (sidebar.isMobile && previousOpenMobile && !openMobile) {
			queueMicrotask(() => ref?.focus());
		}
		previousOpenMobile = openMobile;
	});
</script>

<Button
	bind:ref
	data-sidebar="trigger"
	data-slot="sidebar-trigger"
	aria-expanded={sidebar.isMobile ? sidebar.openMobile : sidebar.open}
	variant="ghost"
	size="icon-sm"
	class={cn("hp:size-7", className)}
	type="button"
	onclick={(e) => {
		onclick?.(e);
		sidebar.toggle();
	}}
	{...restProps}
>
	<PanelLeftIcon  />
	<span class="hp:sr-only">{label}</span>
</Button>

// packages/vue/src/ui/sidebar/SidebarTrigger.vue
<script setup lang="ts">
import type { ComponentPublicInstance, HTMLAttributes } from "vue"
import { ViewVerticalIcon } from '@radix-icons/vue'
import { nextTick, ref, watch } from 'vue'
import { cn } from "@/lib/utils"
import { Button } from '@/ui/button'
import { useSidebar } from "./utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
  label?: string
}>()

const { isMobile, open, openMobile, toggleSidebar } = useSidebar()
const trigger = ref<HTMLButtonElement | ComponentPublicInstance>()

watch(openMobile, (nextOpen, previousOpen) => {
  if (!isMobile.value || !previousOpen || nextOpen) return
  void nextTick(() => {
    const current = trigger.value
    const element = current instanceof HTMLButtonElement ? current : current?.$el
    if (element instanceof HTMLButtonElement) element.focus()
  })
})
</script>

<template>
  <Button
    data-sidebar="trigger"
    data-slot="sidebar-trigger"
    :aria-expanded="isMobile ? openMobile : open"
    ref="trigger"
    variant="ghost"
    size="icon"
    :class="cn('hp:h-7 hp:w-7', props.class)"
    @click="toggleSidebar"
  >
    <ViewVerticalIcon />
    <span class="hp:sr-only">{{ props.label ?? 'Toggle Sidebar' }}</span>
  </Button>
</template>
