// packages/svelte/src/ui/sidebar/sidebar-menu.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "../../lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLUListElement>, HTMLUListElement> = $props();
</script>

<ul
	bind:this={ref}
	data-slot="sidebar-menu"
	data-sidebar="menu"
	class={cn("hp:gap-0 hp:flex hp:w-full hp:min-w-0 hp:flex-col", className)}
	{...restProps}
>
	{@render children?.()}
</ul>

// packages/vue/src/ui/sidebar/SidebarMenu.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <ul
    data-slot="sidebar-menu"
    data-sidebar="menu"
    :class="cn('hp:flex hp:w-full hp:min-w-0 hp:flex-col hp:gap-1', props.class)"
  >
    <slot />
  </ul>
</template>
