// packages/svelte/src/ui/sidebar/sidebar-separator.svelte
<script lang="ts">
	import { Separator } from "../separator/index.js";
	import { cn } from "../../lib/utils.js";
	import type { ComponentProps } from "svelte";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: ComponentProps<typeof Separator> = $props();
</script>

<Separator
	bind:ref
	data-slot="sidebar-separator"
	data-sidebar="separator"
	class={cn("hp:mx-2 hp:bg-sidebar-border hp:w-auto", className)}
	{...restProps}
/>

// packages/vue/src/ui/sidebar/SidebarSeparator.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"
import { Separator } from '@/ui/separator'

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <Separator
    data-slot="sidebar-separator"
    data-sidebar="separator"
    :class="cn('hp:bg-sidebar-border hp:mx-2 hp:w-auto', props.class)"
  >
    <slot />
  </Separator>
</template>
