// packages/svelte/src/ui/dialog/dialog-header.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "../../lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();
</script>

<div
	bind:this={ref}
	data-slot="dialog-header"
	class={cn("hp:gap-2 hp:flex hp:flex-col", className)}
	{...restProps}
>
	{@render children?.()}
</div>

// packages/vue/src/ui/dialog/DialogHeader.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <div
    data-slot="dialog-header"
    :class="cn('hp:flex hp:flex-col hp:gap-2 hp:text-center hp:sm:text-start', props.class)"
  >
    <slot />
  </div>
</template>
