// apps/example-nuxt/app/pages/blog/index.vue
<script setup lang="ts">
import { getExampleBlogIndex } from '../../../server/blog'

const route = useRoute()
const value = (input: unknown): string | null => typeof input === 'string' ? input : null
const blog = computed(() => getExampleBlogIndex({
  category: value(route.query.category),
  tag: value(route.query.tag),
  tenant: value(route.query.tenant),
}))
</script>

<template>
  <main>
    <header>
      <p>Holo Panels example</p>
      <h1>{{ blog.tenant.name }} journal</h1>
      <p>Published records are resolved from the tenant-scoped example domain.</p>
    </header>
    <nav aria-label="Tenant publications">
      <NuxtLink v-for="tenant in blog.tenants" :key="tenant.routeKey" :to="{ path: '/blog', query: { tenant: tenant.routeKey } }">
        {{ tenant.name }}
      </NuxtLink>
    </nav>
    <nav aria-label="Blog filters">
      <NuxtLink :to="{ path: '/blog', query: { tenant: blog.tenant.routeKey } }">All</NuxtLink>
      <NuxtLink v-for="category in blog.categories" :key="category.slug" :to="{ path: '/blog', query: { category: category.slug, tenant: blog.tenant.routeKey } }">
        {{ category.name }}
      </NuxtLink>
      <NuxtLink v-for="tag in blog.tags" :key="tag.slug" :to="{ path: '/blog', query: { tag: tag.slug, tenant: blog.tenant.routeKey } }">
        #{{ tag.name }}
      </NuxtLink>
    </nav>
    <p v-if="blog.posts.length === 0" role="status">No published posts match these filters.</p>
    <section v-else aria-label="Published posts">
      <article v-for="post in blog.posts" :key="post.slug">
        <p>{{ post.category?.name }} · {{ post.tags.map(tag => tag.name).join(', ') }}</p>
        <h2><NuxtLink :to="{ path: `/blog/${post.slug}`, query: { tenant: blog.tenant.routeKey } }">{{ post.title }}</NuxtLink></h2>
        <p>{{ post.excerpt }}</p>
        <p v-if="post.media?.private">Private media is available only inside the authorized panel.</p>
      </article>
    </section>
  </main>
</template>

<style scoped>
main { margin: 0 auto; max-width: 64rem; padding: 3rem 1.5rem; font-family: sans-serif; }
nav { display: flex; flex-wrap: wrap; gap: 1rem; margin: 1rem 0; }
article { border-block-end: 1px solid #d4d4d8; padding-block: 2rem; }
</style>

// apps/example-next/app/blog/page.tsx
import Link from 'next/link'
import { createExampleBlogDomain } from '../../server/domain/blog'

interface BlogIndexProps {
  readonly searchParams?: Promise<Readonly<Record<string, string | readonly string[] | undefined>>>
}

const selectedValue = (value: string | readonly string[] | undefined): string | undefined => (
  typeof value === 'string' ? value : value?.[0]
)

export default async function BlogIndex({ searchParams }: BlogIndexProps) {
  const query = await searchParams
  const categorySlug = selectedValue(query?.category)
  const tagSlug = selectedValue(query?.tag)
  const posts = createExampleBlogDomain().listPublishedPosts('tenant-acme', { categorySlug, tagSlug })

  return (
    <main style={{ fontFamily: 'sans-serif', margin: '0 auto', maxWidth: '64rem', padding: '3rem 1.5rem' }}>
      <header>
        <p>Acme publishing</p>
        <h1>Holo Panels example blog</h1>
        <p>Published content is resolved through the same tenant-scoped domain used by the administration example.</p>
      </header>
      <nav aria-label="Blog filters">
        <Link href="/blog">All</Link>{' · '}
        <Link href="/blog?category=guides">Guides</Link>{' · '}
        <Link href="/blog?category=news">News</Link>{' · '}
        <Link href="/blog?tag=holo">Holo</Link>
      </nav>
      <section aria-label="Published posts">
        {posts.length === 0 ? <p role="status">No published posts match these filters.</p> : posts.map(post => (
          <article key={post.id} style={{ borderBlockEnd: '1px solid #d4d4d8', paddingBlock: '2rem' }}>
            {post.media ? <img alt={post.media.alt} height="180" src={post.media.url} width="320" /> : null}
            <p>{post.category.name} · {post.tags.map(tag => tag.name).join(', ')}</p>
            <h2><Link href={`/blog/${post.slug}`}>{post.title}</Link></h2>
            <p>{post.excerpt}</p>
          </article>
        ))}
      </section>
    </main>
  )
}
