// packages/react/src/ui/field.tsx
import { useMemo } from "react"
import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "../lib/utils"
import { Label } from "./label"
import { Separator } from "./separator"

function FieldSet({ className, ...props }: React.ComponentProps<"fieldset">) {
  return (
    <fieldset
      data-slot="field-set"
      className={cn(
        "hp:flex hp:flex-col hp:gap-6",
        "hp:has-[>[data-slot=checkbox-group]]:gap-3 hp:has-[>[data-slot=radio-group]]:gap-3",
        className
      )}
      {...props}
    />
  )
}

function FieldLegend({
  className,
  variant = "legend",
  ...props
}: React.ComponentProps<"legend"> & { variant?: "legend" | "label" }) {
  return (
    <legend
      data-slot="field-legend"
      data-variant={variant}
      className={cn(
        "hp:mb-3 hp:font-medium",
        "hp:data-[variant=legend]:text-base",
        "hp:data-[variant=label]:text-sm",
        className
      )}
      {...props}
    />
  )
}

function FieldGroup({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="field-group"
      className={cn(
        "hp:group/field-group hp:@container/field-group hp:flex hp:w-full hp:flex-col hp:gap-7 hp:data-[slot=checkbox-group]:gap-3 hp:[&>[data-slot=field-group]]:gap-4",
        className
      )}
      {...props}
    />
  )
}

const fieldVariants = cva(
  "hp:group/field hp:flex hp:w-full hp:gap-3 hp:data-[invalid=true]:text-destructive",
  {
    variants: {
      orientation: {
        vertical: ["flex-col [&>*]:w-full [&>.sr-only]:w-auto"],
        horizontal: [
          "flex-row items-center",
          "[&>[data-slot=field-label]]:flex-auto",
          "has-[>[data-slot=field-content]]:items-start has-[>[data-slot=field-content]]:[&>[role=checkbox],[role=radio]]:mt-px",
        ],
        responsive: [
          "flex-col @md/field-group:flex-row @md/field-group:items-center [&>*]:w-full @md/field-group:[&>*]:w-auto [&>.sr-only]:w-auto",
          "@md/field-group:[&>[data-slot=field-label]]:flex-auto",
          "@md/field-group:has-[>[data-slot=field-content]]:items-start @md/field-group:has-[>[data-slot=field-content]]:[&>[role=checkbox],[role=radio]]:mt-px",
        ],
      },
    },
    defaultVariants: {
      orientation: "vertical",
    },
  }
)

function Field({
  className,
  orientation = "vertical",
  ...props
}: React.ComponentProps<"div"> & VariantProps<typeof fieldVariants>) {
  return (
    <div
      role="group"
      data-slot="field"
      data-orientation={orientation}
      className={cn(fieldVariants({ orientation }), className)}
      {...props}
    />
  )
}

function FieldContent({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="field-content"
      className={cn(
        "hp:group/field-content hp:flex hp:flex-1 hp:flex-col hp:gap-1.5 hp:leading-snug",
        className
      )}
      {...props}
    />
  )
}

function FieldLabel({
  className,
  ...props
}: React.ComponentProps<typeof Label>) {
  return (
    <Label
      data-slot="field-label"
      className={cn(
        "hp:group/field-label hp:peer/field-label hp:flex hp:w-fit hp:gap-2 hp:leading-snug hp:group-data-[disabled=true]/field:opacity-50",
        "hp:has-[>[data-slot=field]]:w-full hp:has-[>[data-slot=field]]:flex-col hp:has-[>[data-slot=field]]:rounded-md hp:has-[>[data-slot=field]]:border hp:[&>*]:data-[slot=field]:p-4",
        "hp:has-data-[state=checked]:border-primary hp:has-data-[state=checked]:bg-primary/5 hp:dark:has-data-[state=checked]:bg-primary/10",
        className
      )}
      {...props}
    />
  )
}

function FieldTitle({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="field-label"
      className={cn(
        "hp:flex hp:w-fit hp:items-center hp:gap-2 hp:text-sm hp:leading-snug hp:font-medium hp:group-data-[disabled=true]/field:opacity-50",
        className
      )}
      {...props}
    />
  )
}

function FieldDescription({ className, ...props }: React.ComponentProps<"p">) {
  return (
    <p
      data-slot="field-description"
      className={cn(
        "hp:text-sm hp:leading-normal hp:font-normal hp:text-muted-foreground hp:group-has-[[data-orientation=horizontal]]/field:text-balance",
        "hp:last:mt-0 hp:nth-last-2:-mt-1 hp:[[data-variant=legend]+&]:-mt-1.5",
        "hp:[&>a]:underline hp:[&>a]:underline-offset-4 hp:[&>a:hover]:text-primary",
        className
      )}
      {...props}
    />
  )
}

function FieldSeparator({
  children,
  className,
  ...props
}: React.ComponentProps<"div"> & {
  children?: React.ReactNode
}) {
  return (
    <div
      data-slot="field-separator"
      data-content={!!children}
      className={cn(
        "hp:relative hp:-my-2 hp:h-5 hp:text-sm hp:group-data-[variant=outline]/field-group:-mb-2",
        className
      )}
      {...props}
    >
      <Separator className="hp:absolute hp:inset-0 hp:top-1/2" />
      {children && (
        <span
          className="hp:relative hp:mx-auto hp:block hp:w-fit hp:bg-background hp:px-2 hp:text-muted-foreground"
          data-slot="field-separator-content"
        >
          {children}
        </span>
      )}
    </div>
  )
}

function FieldError({
  className,
  children,
  errors,
  ...props
}: React.ComponentProps<"div"> & {
  errors?: Array<{ message?: string } | undefined>
}) {
  const content = useMemo(() => {
    if (children) {
      return children
    }

    if (!errors?.length) {
      return null
    }

    const uniqueErrors = [
      ...new Map(errors.map((error) => [error?.message, error])).values(),
    ]

    if (uniqueErrors?.length === 1) {
      return uniqueErrors[0]?.message
    }

    return (
      <ul className="hp:ms-4 hp:flex hp:list-disc hp:flex-col hp:gap-1">
        {uniqueErrors.map(
          (error, index) =>
            error?.message && <li key={index}>{error.message}</li>
        )}
      </ul>
    )
  }, [children, errors])

  if (!content) {
    return null
  }

  return (
    <div
      role="alert"
      data-slot="field-error"
      className={cn("hp:text-sm hp:font-normal hp:text-destructive", className)}
      {...props}
    >
      {content}
    </div>
  )
}

export {
  Field,
  FieldLabel,
  FieldDescription,
  FieldError,
  FieldGroup,
  FieldLegend,
  FieldSeparator,
  FieldSet,
  FieldContent,
  FieldTitle,
}

// packages/svelte/src/ui/field/field.svelte
<script lang="ts" module>
	import { tv, type VariantProps } from "tailwind-variants";

	export const fieldVariants = tv({
		base: "hp:gap-2 hp:data-[invalid=true]:text-destructive hp:group/field hp:flex hp:w-full",
		variants: {
			orientation: {
				vertical: "hp:cn-field-orientation-vertical hp:flex-col hp:[&>*]:w-full hp:[&>.sr-only]:w-auto",
				horizontal:
					"hp:cn-field-orientation-horizontal hp:flex-row hp:items-center hp:has-[>[data-slot=field-content]]:items-start hp:[&>[data-slot=field-label]]:flex-auto hp:has-[>[data-slot=field-content]]:[&>[role=checkbox],[role=radio]]:mt-px",
				responsive:
					"hp:cn-field-orientation-responsive hp:flex-col hp:@md/field-group:flex-row hp:@md/field-group:items-center hp:@md/field-group:has-[>[data-slot=field-content]]:items-start hp:[&>*]:w-full hp:@md/field-group:[&>*]:w-auto hp:[&>.sr-only]:w-auto hp:@md/field-group:[&>[data-slot=field-label]]:flex-auto hp:@md/field-group:has-[>[data-slot=field-content]]:[&>[role=checkbox],[role=radio]]:mt-px",
			},
		},
		defaultVariants: {
			orientation: "vertical",
		},
	});

	export type FieldOrientation = VariantProps<typeof fieldVariants>["orientation"];
</script>

<script lang="ts">
	import { cn, type WithElementRef } from "../../lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		orientation = "vertical",
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> & {
		orientation?: FieldOrientation;
	} = $props();
</script>

<div
	bind:this={ref}
	role="group"
	data-slot="field"
	data-orientation={orientation}
	class={cn(fieldVariants({ orientation }), className)}
	{...restProps}
>
	{@render children?.()}
</div>
