// packages/vue/src/ui/field/FieldLegend.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
  variant?: "legend" | "label"
}>()
</script>

<template>
  <legend
    data-slot="field-legend"
    :data-variant="variant"
    :class="cn(
      'hp:mb-3 hp:font-medium',
      'hp:data-[variant=legend]:text-base',
      'hp:data-[variant=label]:text-sm',
      props.class,
    )"
  >
    <slot />
  </legend>
</template>

// packages/svelte/src/ui/field/field-legend.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "../../lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		variant = "legend",
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLLegendElement>> & {
		variant?: "legend" | "label";
	} = $props();
</script>

<legend
	bind:this={ref}
	data-slot="field-legend"
	data-variant={variant}
	class={cn("hp:mb-1.5 hp:font-medium hp:data-[variant=label]:text-sm hp:data-[variant=legend]:text-base", className)}
	{...restProps}
>
	{@render children?.()}
</legend>
