// apps/example-sveltekit/src/routes/admin/profile/mfa/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte'

  let enabled = false
  let manualKey = ''
  let recoveryCodes: readonly string[] = []
  let enrollmentCode = ''
  let disableCode = ''
  let disableMethod: 'recovery' | 'totp' = 'totp'
  let error = ''

  function cookie(name: string): string {
    const entry = document.cookie.split(';').map(value => value.trim()).find(value => value.startsWith(`${name}=`))
    return entry ? decodeURIComponent(entry.slice(name.length + 1)) : ''
  }

  async function authRequest(operation: string, payload?: object): Promise<Response> {
    return fetch(`/_holo/panels/admin/auth/${operation}`, payload ? {
      body: JSON.stringify(payload),
      headers: { 'content-type': 'application/json', 'x-csrf-token': cookie('XSRF-TOKEN') },
      method: 'POST',
    } : { method: 'GET' })
  }

  onMount(async () => {
    const response = await authRequest('mfa-status')
    if (response.ok) enabled = Boolean((await response.json() as { enabled?: unknown }).enabled)
  })

  async function begin(): Promise<void> {
    const response = await authRequest('mfa-enrollment-begin')
    if (!response.ok) return void (error = 'MFA enrollment failed')
    manualKey = String((await response.json() as { manualKey?: unknown }).manualKey ?? '')
  }

  async function confirm(): Promise<void> {
    const response = await authRequest('mfa-enrollment-confirm', { code: enrollmentCode })
    if (!response.ok) return void (error = 'MFA confirmation failed')
    const result = await response.json() as { recoveryCodes?: unknown }
    recoveryCodes = Array.isArray(result.recoveryCodes) ? result.recoveryCodes.map(String) : []
    enabled = true
  }

  async function disable(): Promise<void> {
    const response = await authRequest('mfa-disable', { code: disableCode, method: disableMethod })
    if (!response.ok) return void (error = 'MFA disable failed')
    enabled = false
    manualKey = ''
    recoveryCodes = []
  }
</script>

<main><h1>Multi-factor authentication</h1><p>MFA is {enabled ? 'enabled' : 'disabled'}.</p>{#if !enabled && !manualKey}<button type="button" onclick={begin}>Begin enrollment</button>{/if}{#if manualKey}<p>Manual key: <code data-testid="mfa-manual-key">{manualKey}</code></p><form onsubmit={(event) => { event.preventDefault(); void confirm() }}><label>Authentication code<input bind:value={enrollmentCode} name="code" inputmode="numeric" required></label><button type="submit">Confirm enrollment</button></form>{/if}{#if recoveryCodes.length}<section aria-label="Recovery codes"><h2>Recovery codes</h2><ul>{#each recoveryCodes as code (code)}<li>{code}</li>{/each}</ul></section>{/if}{#if enabled}<form onsubmit={(event) => { event.preventDefault(); void disable() }}><label>Disable method<select bind:value={disableMethod} name="method"><option value="totp">Authenticator code</option><option value="recovery">Recovery code</option></select></label><label>Disable code<input bind:value={disableCode} name="code" required></label><button type="submit">Disable MFA</button></form>{/if}{#if error}<p role="alert">{error}</p>{/if}</main>

// apps/example-next/app/admin/profile/mfa/page.tsx
'use client'

import { useEffect, useState, type FormEvent } from 'react'

function cookie(name: string): string {
  const entry = document.cookie.split(';').map(value => value.trim()).find(value => value.startsWith(`${name}=`))
  return entry ? decodeURIComponent(entry.slice(name.length + 1)) : ''
}

async function authRequest(operation: string, payload?: object): Promise<Response> {
  return fetch(`/_holo/panels/admin/auth/${operation}`, payload ? {
    body: JSON.stringify(payload),
    headers: { 'content-type': 'application/json', 'x-csrf-token': cookie('XSRF-TOKEN') },
    method: 'POST',
  } : { method: 'GET' })
}

export default function MultiFactorPage() {
  const [enabled, setEnabled] = useState(false)
  const [manualKey, setManualKey] = useState('')
  const [recoveryCodes, setRecoveryCodes] = useState<readonly string[]>([])
  const [error, setError] = useState('')

  useEffect(() => {
    void authRequest('mfa-status').then(async response => {
      if (response.ok) setEnabled(Boolean((await response.json() as { enabled?: unknown }).enabled))
    })
  }, [])

  async function begin(): Promise<void> {
    const response = await authRequest('mfa-enrollment-begin')
    if (!response.ok) return setError('MFA enrollment failed')
    setManualKey(String((await response.json() as { manualKey?: unknown }).manualKey ?? ''))
  }

  async function confirm(event: FormEvent<HTMLFormElement>): Promise<void> {
    event.preventDefault()
    const code = String(new FormData(event.currentTarget).get('code') ?? '')
    const response = await authRequest('mfa-enrollment-confirm', { code })
    if (!response.ok) return setError('MFA confirmation failed')
    const result = await response.json() as { recoveryCodes?: unknown }
    setRecoveryCodes(Array.isArray(result.recoveryCodes) ? result.recoveryCodes.map(String) : [])
    setEnabled(true)
  }

  async function disable(event: FormEvent<HTMLFormElement>): Promise<void> {
    event.preventDefault()
    const values = new FormData(event.currentTarget)
    const response = await authRequest('mfa-disable', { code: values.get('code'), method: values.get('method') })
    if (!response.ok) return setError('MFA disable failed')
    setEnabled(false)
    setManualKey('')
    setRecoveryCodes([])
  }

  return <main><h1>Multi-factor authentication</h1><p>MFA is {enabled ? 'enabled' : 'disabled'}.</p>{!enabled && !manualKey ? <button type="button" onClick={begin}>Begin enrollment</button> : null}{manualKey ? <><p>Manual key: <code data-testid="mfa-manual-key">{manualKey}</code></p><form onSubmit={confirm}><label>Authentication code<input name="code" inputMode="numeric" required /></label><button type="submit">Confirm enrollment</button></form></> : null}{recoveryCodes.length ? <section aria-label="Recovery codes"><h2>Recovery codes</h2><ul>{recoveryCodes.map(code => <li key={code}>{code}</li>)}</ul></section> : null}{enabled ? <form onSubmit={disable}><label>Disable method<select name="method"><option value="totp">Authenticator code</option><option value="recovery">Recovery code</option></select></label><label>Disable code<input name="code" required /></label><button type="submit">Disable MFA</button></form> : null}{error ? <p role="alert">{error}</p> : null}</main>
}
