// packages/vue/src/ui/empty/Empty.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <div
    data-slot="empty"
    :class="cn(
      'hp:flex hp:min-w-0 hp:flex-1 hp:flex-col hp:items-center hp:justify-center hp:gap-6 hp:text-balance hp:rounded-lg hp:border-dashed hp:p-6 hp:text-center hp:md:p-12',
      props.class,
    )"
  >
    <slot />
  </div>
</template>

// packages/svelte/src/ui/empty/empty.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "../../lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();
</script>

<div
	bind:this={ref}
	data-slot="empty"
	class={cn(
		"hp:gap-4 hp:rounded-xl hp:border-dashed hp:p-6 hp:flex hp:w-full hp:min-w-0 hp:flex-1 hp:flex-col hp:items-center hp:justify-center hp:text-center hp:text-balance",
		className
	)}
	{...restProps}
>
	{@render children?.()}
</div>
