// packages/vue/src/ui/empty/EmptyDescription.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <p
    data-slot="empty-description"
    :class="cn(
      'hp:text-muted-foreground hp:[&>a:hover]:text-primary hp:text-sm/relaxed hp:[&>a]:underline hp:[&>a]:underline-offset-4',
      $attrs.class ?? 'hp:',
    )"
  >
    <slot />
  </p>
</template>

// packages/svelte/src/ui/empty/empty-description.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "../../lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();
</script>

<div
	bind:this={ref}
	data-slot="empty-description"
	class={cn(
		"hp:text-sm/relaxed hp:text-sm/relaxed hp:text-muted-foreground hp:[&>a]:underline hp:[&>a]:underline-offset-4 hp:[&>a:hover]:text-primary",
		className
	)}
	{...restProps}
>
	{@render children?.()}
</div>
