// packages/vue/src/ui/empty/EmptyHeader.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <div
    data-slot="empty-header"
    :class="cn(
      'hp:flex hp:max-w-sm hp:flex-col hp:items-center hp:gap-2 hp:text-center',
      props.class,
    )"
  >
    <slot />
  </div>
</template>

// packages/svelte/src/ui/empty/empty-header.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "../../lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();
</script>

<div
	bind:this={ref}
	data-slot="empty-header"
	class={cn("hp:gap-2 hp:flex hp:max-w-sm hp:flex-col hp:items-center", className)}
	{...restProps}
>
	{@render children?.()}
</div>
