// apps/example-next/resources/panels/renderers/next/widgets/admin-content-notice.tsx
import type { ReactCustomWidgetProps } from '@holo-js/panels-react'

export default function ContentNotice({ properties }: ReactCustomWidgetProps) {
  return <div><p>{String(properties.message ?? '')}</p><details><summary>Publishing details</summary><p>{String(properties.detail ?? '')}</p></details></div>
}

// apps/example-nuxt/resources/panels/renderers/nuxt/widgets/admin-content-notice.vue
<script setup lang="ts">
import type { VueCustomWidgetProps } from '@holo-js/panels-vue'

defineProps<VueCustomWidgetProps>()
</script>

<template>
  <div><p>{{ data.properties.message }}</p><details><summary>Publishing details</summary><p>{{ data.properties.detail }}</p></details></div>
</template>
