// packages/vue/src/ui/card/Card.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <div
    data-slot="card"
    :class="
      cn(
        'hp:bg-card hp:text-card-foreground hp:flex hp:flex-col hp:gap-6 hp:rounded-xl hp:border hp:py-6 hp:shadow-sm',
        props.class,
      )
    "
  >
    <slot />
  </div>
</template>

// packages/react/src/ui/card.tsx
import * as React from "react"

import { cn } from "../lib/utils"

function Card({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card"
      className={cn(
        "hp:flex hp:flex-col hp:gap-6 hp:rounded-xl hp:border hp:bg-card hp:py-6 hp:text-card-foreground hp:shadow-sm",
        className
      )}
      {...props}
    />
  )
}

function CardHeader({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-header"
      className={cn(
        "hp:@container/card-header hp:grid hp:auto-rows-min hp:grid-rows-[auto_auto] hp:items-start hp:gap-2 hp:px-6 hp:has-data-[slot=card-action]:grid-cols-[1fr_auto] hp:[.border-b]:pb-6",
        className
      )}
      {...props}
    />
  )
}

function CardTitle({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-title"
      className={cn("hp:leading-none hp:font-semibold", className)}
      {...props}
    />
  )
}

function CardDescription({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-description"
      className={cn("hp:text-sm hp:text-muted-foreground", className)}
      {...props}
    />
  )
}

function CardAction({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-action"
      className={cn(
        "hp:col-start-2 hp:row-span-2 hp:row-start-1 hp:self-start hp:justify-self-end",
        className
      )}
      {...props}
    />
  )
}

function CardContent({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-content"
      className={cn("hp:px-6", className)}
      {...props}
    />
  )
}

function CardFooter({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-footer"
      className={cn("hp:flex hp:items-center hp:px-6 hp:[.border-t]:pt-6", className)}
      {...props}
    />
  )
}

export {
  Card,
  CardHeader,
  CardFooter,
  CardTitle,
  CardAction,
  CardDescription,
  CardContent,
}
