// packages/vue/src/ui/separator/Separator.vue
<script setup lang="ts">
import type { SeparatorProps } from "reka-ui"
import type { HTMLAttributes } from "vue"
import { reactiveOmit } from "@vueuse/core"
import { Separator } from "reka-ui"
import { cn } from "@/lib/utils"

const props = withDefaults(defineProps<
  SeparatorProps & { class?: HTMLAttributes["class"] }
>(), {
  orientation: "horizontal",
  decorative: true,
})

const delegatedProps = reactiveOmit(props, "class")
</script>

<template>
  <Separator
    data-slot="separator"
    v-bind="delegatedProps"
    :class="
      cn(
        'hp:bg-border hp:shrink-0 hp:data-[orientation=horizontal]:h-px hp:data-[orientation=horizontal]:w-full hp:data-[orientation=vertical]:h-full hp:data-[orientation=vertical]:w-px',
        props.class,
      )
    "
  />
</template>

// packages/react/src/ui/separator.tsx
import * as React from "react"
import { Separator as SeparatorPrimitive } from "radix-ui"

import { cn } from "../lib/utils"

function Separator({
  className,
  orientation = "horizontal",
  decorative = true,
  ...props
}: React.ComponentProps<typeof SeparatorPrimitive.Root>) {
  return (
    <SeparatorPrimitive.Root
      data-slot="separator"
      decorative={decorative}
      orientation={orientation}
      className={cn(
        "hp:shrink-0 hp:bg-border hp:data-[orientation=horizontal]:h-px hp:data-[orientation=horizontal]:w-full hp:data-[orientation=vertical]:h-full hp:data-[orientation=vertical]:w-px",
        className
      )}
      {...props}
    />
  )
}

export { Separator }
