// packages/vue/src/ui/sonner/Sonner.vue
<script lang="ts" setup>
import type { ToasterProps } from "vue-sonner"
import { CheckCircledIcon, InfoCircledIcon, ReloadIcon, CrossCircledIcon, ExclamationTriangleIcon, Cross2Icon } from '@radix-icons/vue'
import { Toaster as Sonner } from "vue-sonner"
import { cn } from "@/lib/utils"

const props = defineProps<ToasterProps>()
</script>

<template>
  <Sonner
    :class="cn('hp:toaster hp:group', props.class)"
    :style="{
      '--normal-bg': 'var(--popover)',
      '--normal-text': 'var(--popover-foreground)',
      '--normal-border': 'var(--border)',
      '--border-radius': 'var(--radius)',
    }"
    v-bind="props"
  >
    <template #success-icon>
      <CheckCircledIcon class="hp:size-4" />
    </template>
    <template #info-icon>
      <InfoCircledIcon class="hp:size-4" />
    </template>
    <template #warning-icon>
      <ExclamationTriangleIcon class="hp:size-4" />
    </template>
    <template #error-icon>
      <CrossCircledIcon class="hp:size-4" />
    </template>
    <template #loading-icon>
      <div>
        <ReloadIcon class="hp:size-4 hp:animate-spin" />
      </div>
    </template>
    <template #close-icon>
      <Cross2Icon class="hp:size-4" />
    </template>
  </Sonner>
</template>

// packages/react/src/ui/sonner.tsx
import {
  CircleCheckIcon,
  InfoIcon,
  Loader2Icon,
  OctagonXIcon,
  TriangleAlertIcon,
} from "lucide-react"
import { Toaster as Sonner, type ToasterProps } from "sonner"

const Toaster = ({ ...props }: ToasterProps) => {
  return (
    <Sonner
      theme="system"
      className="hp:toaster hp:group"
      icons={{
        success: <CircleCheckIcon className="hp:size-4" />,
        info: <InfoIcon className="hp:size-4" />,
        warning: <TriangleAlertIcon className="hp:size-4" />,
        error: <OctagonXIcon className="hp:size-4" />,
        loading: <Loader2Icon className="hp:size-4 hp:animate-spin" />,
      }}
      style={
        {
          "--normal-bg": "var(--hp-popover)",
          "--normal-text": "var(--hp-popover-foreground)",
          "--normal-border": "var(--hp-border)",
          "--border-radius": "var(--hp-radius)",
        } as React.CSSProperties
      }
      {...props}
    />
  )
}

export { Toaster }
