// packages/svelte/src/ui/dropdown-menu/dropdown-menu-radio-item.svelte
<script lang="ts">
	import { DropdownMenu as DropdownMenuPrimitive } from "bits-ui";
	import CheckIcon from '@lucide/svelte/icons/check';
	import { cn, type WithoutChild } from "../../lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		children: childrenProp,
		...restProps
	}: WithoutChild<DropdownMenuPrimitive.RadioItemProps> = $props();
</script>

<DropdownMenuPrimitive.RadioItem
	bind:ref
	data-slot="dropdown-menu-radio-item"
	class={cn(
		"hp:gap-1.5 hp:rounded-md hp:py-1 hp:pr-8 hp:pl-1.5 hp:text-sm hp:focus:bg-accent hp:focus:text-accent-foreground hp:focus:**:text-accent-foreground hp:data-inset:pl-7 hp:[&_svg:not([class*='size-'])]:size-4 hp:relative hp:flex hp:cursor-default hp:items-center hp:outline-hidden hp:select-none hp:data-[disabled]:pointer-events-none hp:data-[disabled]:opacity-50 hp:[&_svg]:pointer-events-none hp:[&_svg]:shrink-0",
		className
	)}
	{...restProps}
>
	{#snippet children({ checked })}
		<span
			class="hp:absolute hp:right-2 hp:flex hp:items-center hp:justify-center hp:pointer-events-none"
			data-slot="dropdown-menu-radio-item-indicator"
		>
			{#if checked}
				<CheckIcon  />
			{/if}
		</span>
		{@render childrenProp?.({ checked })}
	{/snippet}
</DropdownMenuPrimitive.RadioItem>

// packages/vue/src/ui/dropdown-menu/DropdownMenuRadioItem.vue
<script setup lang="ts">
import type { DropdownMenuRadioItemEmits, DropdownMenuRadioItemProps } from "reka-ui"
import type { HTMLAttributes } from "vue"
import { DotFilledIcon } from '@radix-icons/vue'
import { reactiveOmit } from "@vueuse/core"
import {
  DropdownMenuItemIndicator,
  DropdownMenuRadioItem,
  useForwardPropsEmits,
} from "reka-ui"
import { cn } from "@/lib/utils"

const props = defineProps<DropdownMenuRadioItemProps & { class?: HTMLAttributes["class"] }>()

const emits = defineEmits<DropdownMenuRadioItemEmits>()

const delegatedProps = reactiveOmit(props, "class")

const forwarded = useForwardPropsEmits(delegatedProps, emits)
</script>

<template>
  <DropdownMenuRadioItem
    data-slot="dropdown-menu-radio-item"
    v-bind="forwarded"
    :class="cn(
      `hp:focus:bg-accent hp:focus:text-accent-foreground hp:relative hp:flex hp:cursor-default hp:items-center hp:gap-2 hp:rounded-sm hp:py-1.5 hp:pe-2 hp:ps-8 hp:text-sm hp:outline-hidden hp:select-none hp:data-[disabled]:pointer-events-none hp:data-[disabled]:opacity-50 hp:[&_svg]:pointer-events-none hp:[&_svg]:shrink-0 hp:[&_svg:not([class*='size-'])]:size-4`,
      props.class,
    )"
  >
    <span class="hp:pointer-events-none hp:absolute hp:start-2 hp:flex hp:size-3.5 hp:items-center hp:justify-center">
      <DropdownMenuItemIndicator>
        <slot name="indicator-icon">
          <DotFilledIcon class="hp:size-2 hp:fill-current" />
        </slot>
      </DropdownMenuItemIndicator>
    </span>
    <slot />
  </DropdownMenuRadioItem>
</template>
