// packages/svelte/src/ui/dropdown-menu/dropdown-menu-shortcut.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "../../lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLSpanElement>> = $props();
</script>

<span
	bind:this={ref}
	data-slot="dropdown-menu-shortcut"
	class={cn("hp:ml-auto hp:text-xs hp:tracking-widest hp:text-muted-foreground hp:group-focus/dropdown-menu-item:text-accent-foreground", className)}
	{...restProps}
>
	{@render children?.()}
</span>

// packages/vue/src/ui/dropdown-menu/DropdownMenuShortcut.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <span
    data-slot="dropdown-menu-shortcut"
    :class="cn('hp:text-muted-foreground hp:ml-auto hp:text-xs hp:tracking-widest', props.class)"
  >
    <slot />
  </span>
</template>
