// packages/svelte/src/ui/select/select-label.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "../../lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> & {} = $props();
</script>

<div
	bind:this={ref}
	data-slot="select-label"
	class={cn("hp:px-1.5 hp:py-1 hp:text-xs hp:text-muted-foreground", className)}
	{...restProps}
>
	{@render children?.()}
</div>

// packages/vue/src/ui/select/SelectLabel.vue
<script setup lang="ts">
import type { SelectLabelProps } from "reka-ui"
import type { HTMLAttributes } from "vue"
import { SelectLabel } from "reka-ui"
import { cn } from "@/lib/utils"

const props = defineProps<SelectLabelProps & { class?: HTMLAttributes["class"] }>()
</script>

<template>
  <SelectLabel
    data-slot="select-label"
    :class="cn('hp:text-muted-foreground hp:px-2 hp:py-1.5 hp:text-xs', props.class)"
  >
    <slot />
  </SelectLabel>
</template>
