// packages/react/src/ui/alert.tsx
import * as React from "react"
import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "../lib/utils"

const alertVariants = cva(
  "hp:relative hp:grid hp:w-full hp:grid-cols-[0_1fr] hp:items-start hp:gap-y-0.5 hp:rounded-lg hp:border hp:px-4 hp:py-3 hp:text-sm hp:has-[>svg]:grid-cols-[calc(var(--spacing)*4)_1fr] hp:has-[>svg]:gap-x-3 hp:[&>svg]:size-4 hp:[&>svg]:translate-y-0.5 hp:[&>svg]:text-current",
  {
    variants: {
      variant: {
        default: "hp:bg-card hp:text-card-foreground",
        destructive:
          "hp:bg-card hp:text-destructive hp:*:data-[slot=alert-description]:text-destructive/90 hp:[&>svg]:text-current",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  }
)

function Alert({
  className,
  variant,
  ...props
}: React.ComponentProps<"div"> & VariantProps<typeof alertVariants>) {
  return (
    <div
      data-slot="alert"
      role="alert"
      className={cn(alertVariants({ variant }), className)}
      {...props}
    />
  )
}

function AlertTitle({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="alert-title"
      className={cn(
        "hp:col-start-2 hp:line-clamp-1 hp:min-h-4 hp:font-medium hp:tracking-tight",
        className
      )}
      {...props}
    />
  )
}

function AlertDescription({
  className,
  ...props
}: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="alert-description"
      className={cn(
        "hp:col-start-2 hp:grid hp:justify-items-start hp:gap-1 hp:text-sm hp:text-muted-foreground hp:[&_p]:leading-relaxed",
        className
      )}
      {...props}
    />
  )
}

export { Alert, AlertTitle, AlertDescription }

// packages/svelte/src/ui/alert/alert.svelte
<script lang="ts" module>
	import { type VariantProps, tv } from "tailwind-variants";

	export const alertVariants = tv({
		base: "hp:grid hp:gap-0.5 hp:rounded-lg hp:border hp:px-2.5 hp:py-2 hp:text-left hp:text-sm hp:has-data-[slot=alert-action]:relative hp:has-data-[slot=alert-action]:pr-18 hp:has-[>svg]:grid-cols-[auto_1fr] hp:has-[>svg]:gap-x-2 hp:*:[svg]:row-span-2 hp:*:[svg]:translate-y-0.5 hp:*:[svg]:text-current hp:*:[svg:not([class*='size-'])]:size-4 hp:group/alert hp:relative hp:w-full",
		variants: {
			variant: {
				default: "hp:bg-card hp:text-card-foreground",
				destructive: "hp:bg-card hp:text-destructive hp:*:data-[slot=alert-description]:text-destructive/90 hp:*:[svg]:text-current",
			},
		},
		defaultVariants: {
			variant: "default",
		},
	});

	export type AlertVariant = VariantProps<typeof alertVariants>["variant"];
</script>

<script lang="ts">
	import { cn, type WithElementRef } from "../../lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		variant = "default",
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> & {
		variant?: AlertVariant;
	} = $props();
</script>

<div
	bind:this={ref}
	data-slot="alert"
	role="alert"
	class={cn(alertVariants({ variant }), className)}
	{...restProps}
>
	{@render children?.()}
</div>
