// packages/svelte/src/ui/skeleton/skeleton.svelte
<script lang="ts">
	import { cn, type WithElementRef, type WithoutChildren } from "../../lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: WithoutChildren<WithElementRef<HTMLAttributes<HTMLDivElement>>> = $props();
</script>

<div
	bind:this={ref}
	data-slot="skeleton"
	class={cn("hp:rounded-md hp:bg-muted hp:animate-pulse", className)}
	{...restProps}
></div>

// packages/vue/src/ui/skeleton/Skeleton.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

interface SkeletonProps {
  class?: HTMLAttributes["class"]
}

const props = defineProps<SkeletonProps>()
</script>

<template>
  <div
    data-slot="skeleton"
    :class="cn('hp:animate-pulse hp:rounded-md hp:bg-primary/10', props.class)"
  />
</template>
