// packages/svelte/src/ui/field/field-content.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "../../lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();
</script>

<div
	bind:this={ref}
	data-slot="field-content"
	class={cn("hp:gap-0.5 hp:group/field-content hp:flex hp:flex-1 hp:flex-col hp:leading-snug", className)}
	{...restProps}
>
	{@render children?.()}
</div>

// packages/vue/src/ui/field/FieldContent.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <div
    data-slot="field-content"
    :class="cn(
      'hp:group/field-content hp:flex hp:flex-1 hp:flex-col hp:gap-1.5 hp:leading-snug',
      props.class,
    )"
  >
    <slot />
  </div>
</template>
