// apps/example-nuxt/app/pages/admin/profile/mfa/index.vue
<!-- @holo-panels-managed sha256:903cca96faeea7fd2f39957013f382d825da000e31c5bfa3c2dd33afeb0ded3a -->
<script setup lang="ts">
import '../../../../../.holo-js/generated/panels/theme.css'
import { PanelMultiFactorPage } from '@holo-js/panels-nuxt'
</script>

<template>
  <PanelMultiFactorPage panel-id="admin" />
</template>

// apps/example-sveltekit/src/routes/admin/profile/mfa/+page.svelte
<!-- @holo-panels-managed sha256:0f8f94f161fac5e40d27fb41c48431ee6bdf5b799ae8d0cc14a025d8d4fc96b9 -->
<script lang="ts">
  import '../../../../../.holo-js/generated/panels/theme.css'
  import { PanelMultiFactorPage } from '@holo-js/panels-sveltekit'
</script>

<PanelMultiFactorPage panelId="admin" />
