// packages/vue/src/ui/avatar/Avatar.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { AvatarRoot } from "reka-ui"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <AvatarRoot
    data-slot="avatar"
    :class="cn('hp:relative hp:flex hp:size-8 hp:shrink-0 hp:overflow-hidden hp:rounded-full', props.class)"
  >
    <slot />
  </AvatarRoot>
</template>

// packages/svelte/src/ui/avatar/avatar.svelte
<script lang="ts">
	import { Avatar as AvatarPrimitive } from "bits-ui";
	import { cn } from "../../lib/utils.js";

	let {
		ref = $bindable(null),
		loadingStatus = $bindable("loading"),
		size = "default",
		class: className,
		...restProps
	}: AvatarPrimitive.RootProps & {
		size?: "default" | "sm" | "lg";
	} = $props();
</script>

<AvatarPrimitive.Root
	bind:ref
	bind:loadingStatus
	data-slot="avatar"
	data-size={size}
	class={cn(
		"hp:size-8 hp:rounded-full hp:after:rounded-full hp:data-[size=lg]:size-10 hp:data-[size=sm]:size-6 hp:group/avatar hp:relative hp:flex hp:shrink-0 hp:select-none hp:after:absolute hp:after:inset-0 hp:after:border hp:after:border-border hp:after:mix-blend-darken hp:dark:after:mix-blend-lighten",
		className
	)}
	{...restProps}
/>
