// packages/svelte/src/components/ErrorBoundary.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import Button from './Button.svelte'
  interface Props { children?: Snippet; error?: string; fallback?: string; onerror?: (error: unknown) => void }
  let { children, error, fallback = 'This panel could not be rendered.', onerror }: Props = $props()
</script>

{#snippet failed(error: unknown, reset: () => void)}
  <section class="hp-error-boundary" data-panels-component="error-boundary" role="alert"><p>{fallback}</p><Button onclick={reset} type="button">Try again</Button></section>
{/snippet}

{#if error}
  <section class="hp-error-boundary" data-panels-component="error-boundary" role="alert"><p>{error}</p></section>
{:else}
  <svelte:boundary {failed} {onerror}>{@render children?.()}</svelte:boundary>
{/if}

// packages/react/src/error-boundary.tsx
import { Component, createElement, type ErrorInfo, type ReactNode } from 'react'

export interface PanelsErrorBoundaryProps {
  readonly children?: ReactNode
  readonly fallback: ReactNode | ((error: Error) => ReactNode)
  readonly onError?: (error: Error, info: ErrorInfo) => void
}

interface PanelsErrorBoundaryState {
  readonly error?: Error
}

export class PanelsErrorBoundary extends Component<PanelsErrorBoundaryProps, PanelsErrorBoundaryState> {
  override state: PanelsErrorBoundaryState = {}

  static getDerivedStateFromError(error: Error): PanelsErrorBoundaryState {
    return { error }
  }

  override componentDidCatch(error: Error, info: ErrorInfo): void {
    this.props.onError?.(error, info)
  }

  override render(): ReactNode {
    const { error } = this.state
    if (!error) return this.props.children
    return createElement('div', { 'data-panels-component': 'error-boundary', role: 'alert' },
      typeof this.props.fallback === 'function' ? this.props.fallback(error) : this.props.fallback)
  }
}
