// packages/svelte/src/components/PageActions.svelte
<script lang="ts">
  import { Portal } from 'bits-ui'
  import type { Snippet } from 'svelte'

  let { children, to }: { readonly children?: Snippet, readonly to?: HTMLElement } = $props()
</script>

{#if to}
  <Portal {to}>
    <div class="hp-page-actions hp:flex hp:flex-wrap hp:items-center hp:justify-end hp:gap-2" data-slot="page-actions">{@render children?.()}</div>
  </Portal>
{:else if to === undefined}
  <div class="hp-page-actions hp:flex hp:flex-wrap hp:items-center hp:justify-end hp:gap-2" data-slot="page-actions">{@render children?.()}</div>
{/if}

// packages/react/src/page-actions.tsx
import { createContext, useContext, type ReactNode } from 'react'
import { createPortal } from 'react-dom'

const PageActionsContext = createContext<HTMLElement | null | undefined>(undefined)

export interface PanelsPageActionsProviderProps {
  readonly children?: ReactNode
  readonly container: HTMLElement | null
}

export function PanelsPageActionsProvider({ children, container }: PanelsPageActionsProviderProps): ReactNode {
  return <PageActionsContext.Provider value={container}>{children}</PageActionsContext.Provider>
}

export function PanelsPageActions({ children }: { readonly children?: ReactNode }): ReactNode {
  const container = useContext(PageActionsContext)
  const actions = <div className="hp-page-actions hp:flex hp:flex-wrap hp:items-center hp:justify-end hp:gap-2" data-slot="page-actions">{children}</div>
  if (container === undefined) return actions
  return container ? createPortal(actions, container) : null
}
