// packages/react/src/ui/sonner.tsx
import {
  CircleCheckIcon,
  InfoIcon,
  Loader2Icon,
  OctagonXIcon,
  TriangleAlertIcon,
} from "lucide-react"
import { Toaster as Sonner, type ToasterProps } from "sonner"

const Toaster = ({ ...props }: ToasterProps) => {
  return (
    <Sonner
      theme="system"
      className="hp:toaster hp:group"
      icons={{
        success: <CircleCheckIcon className="hp:size-4" />,
        info: <InfoIcon className="hp:size-4" />,
        warning: <TriangleAlertIcon className="hp:size-4" />,
        error: <OctagonXIcon className="hp:size-4" />,
        loading: <Loader2Icon className="hp:size-4 hp:animate-spin" />,
      }}
      style={
        {
          "--normal-bg": "var(--hp-popover)",
          "--normal-text": "var(--hp-popover-foreground)",
          "--normal-border": "var(--hp-border)",
          "--border-radius": "var(--hp-radius)",
        } as React.CSSProperties
      }
      {...props}
    />
  )
}

export { Toaster }

// packages/svelte/src/ui/sonner/sonner.svelte
<script lang="ts">
	import { mode } from "mode-watcher";
	import { Toaster as Sonner, type ToasterProps as SonnerProps } from "svelte-sonner";
	import Loader2Icon from '@lucide/svelte/icons/loader-2';
	import CircleCheckIcon from '@lucide/svelte/icons/circle-check';
	import OctagonXIcon from '@lucide/svelte/icons/octagon-x';
	import InfoIcon from '@lucide/svelte/icons/info';
	import TriangleAlertIcon from '@lucide/svelte/icons/triangle-alert';

	let { ...restProps }: SonnerProps = $props();
</script>

<Sonner
	theme={mode.current}
	class="hp:toaster hp:group"
	style="hp:--normal-bg: hp:var(--color-popover); hp:--normal-text: hp:var(--color-popover-foreground); hp:--normal-border: hp:var(--color-border);"
	{...restProps}
>
	{#snippet loadingIcon()}
		<Loader2Icon class="hp:size-4 hp:animate-spin" />
	{/snippet}
	{#snippet successIcon()}
		<CircleCheckIcon class="hp:size-4" />
	{/snippet}
	{#snippet errorIcon()}
		<OctagonXIcon class="hp:size-4" />
	{/snippet}
	{#snippet infoIcon()}
		<InfoIcon class="hp:size-4" />
	{/snippet}
	{#snippet warningIcon()}
		<TriangleAlertIcon class="hp:size-4" />
	{/snippet}
</Sonner>
