// packages/svelte/src/ui/table/table-cell.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "../../lib/utils.js";
	import type { HTMLTdAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLTdAttributes> = $props();
</script>

<td bind:this={ref} data-slot="table-cell" class={cn("hp:p-2 hp:align-middle hp:whitespace-nowrap hp:[&:has([role=checkbox])]:pr-0", className)} {...restProps}>
	{@render children?.()}
</td>

// packages/vue/src/ui/table/TableCell.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <td
    data-slot="table-cell"
    :class="
      cn(
        'hp:px-3 hp:py-2 hp:align-middle hp:whitespace-nowrap hp:[&:has([role=checkbox])]:pe-0 hp:*:[[role=checkbox]]:translate-y-0.5',
        props.class,
      )
    "
  >
    <slot />
  </td>
</template>
