// packages/svelte/src/ui/table/table-footer.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "../../lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLTableSectionElement>> = $props();
</script>

<tfoot
	bind:this={ref}
	data-slot="table-footer"
	class={cn("hp:border-t hp:bg-muted/50 hp:font-medium hp:[&>tr]:last:border-b-0", className)}
	{...restProps}
>
	{@render children?.()}
</tfoot>

// packages/vue/src/ui/table/TableFooter.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <tfoot
    data-slot="table-footer"
    :class="cn('hp:bg-muted/50 hp:border-t hp:font-medium hp:[&>tr]:last:border-b-0', props.class)"
  >
    <slot />
  </tfoot>
</template>
