// packages/vue/src/ui/dialog/DialogDescription.vue
<script setup lang="ts">
import type { DialogDescriptionProps } from "reka-ui"
import type { HTMLAttributes } from "vue"
import { reactiveOmit } from "@vueuse/core"
import { DialogDescription, useForwardProps } from "reka-ui"
import { cn } from "@/lib/utils"

const props = defineProps<DialogDescriptionProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = reactiveOmit(props, "class")

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
  <DialogDescription
    data-slot="dialog-description"
    v-bind="forwardedProps"
    :class="cn('hp:text-muted-foreground hp:text-sm', props.class)"
  >
    <slot />
  </DialogDescription>
</template>

// packages/svelte/src/ui/dialog/dialog-description.svelte
<script lang="ts">
	import { Dialog as DialogPrimitive } from "bits-ui";
	import { cn } from "../../lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: DialogPrimitive.DescriptionProps = $props();
</script>

<DialogPrimitive.Description
	bind:ref
	data-slot="dialog-description"
	class={cn("hp:text-sm hp:text-muted-foreground hp:*:[a]:underline hp:*:[a]:underline-offset-3 hp:*:[a]:hover:text-foreground", className)}
	{...restProps}
/>
