// packages/svelte/src/ui/input-group/input-group-text.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "../../lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLSpanElement>> = $props();
</script>

<span
	bind:this={ref}
	class={cn("hp:gap-2 hp:text-sm hp:text-muted-foreground hp:[&_svg:not([class*='size-'])]:size-4 hp:flex hp:items-center hp:[&_svg]:pointer-events-none", className)}
	{...restProps}
>
	{@render children?.()}
</span>

// packages/vue/src/ui/input-group/InputGroupText.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { cn } from '../../lib/utils'

const props = defineProps<{ class?: HTMLAttributes['class'] }>()
</script>

<template>
  <span :class="cn('hp:flex hp:items-center hp:gap-2 hp:text-sm hp:text-muted-foreground hp:[&_svg]:pointer-events-none hp:[&_svg:not([class*=size-])]:size-4', props.class)"><slot /></span>
</template>
