// packages/svelte/src/ui/input-group/input-group.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "../../lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...props
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();
</script>

<div
	bind:this={ref}
	data-slot="input-group"
	role="group"
	class={cn(
		"hp:group/input-group hp:h-9 hp:rounded-md hp:border hp:border-input hp:transition-colors hp:in-data-[slot=combobox-content]:focus-within:border-inherit hp:in-data-[slot=combobox-content]:focus-within:ring-0 hp:has-disabled:bg-input/50 hp:has-disabled:opacity-50 hp:has-[[data-slot=input-group-control]:focus-visible]:border-ring hp:has-[[data-slot=input-group-control]:focus-visible]:ring-3 hp:has-[[data-slot=input-group-control]:focus-visible]:ring-ring/50 hp:has-[[data-slot][aria-invalid=true]]:border-destructive hp:has-[[data-slot][aria-invalid=true]]:ring-3 hp:has-[[data-slot][aria-invalid=true]]:ring-destructive/20 hp:has-[>[data-align=block-end]]:h-auto hp:has-[>[data-align=block-end]]:flex-col hp:has-[>[data-align=block-start]]:h-auto hp:has-[>[data-align=block-start]]:flex-col hp:dark:bg-input/30 hp:dark:has-disabled:bg-input/80 hp:dark:has-[[data-slot][aria-invalid=true]]:ring-destructive/40 hp:has-[>[data-align=block-end]]:[&>input]:pt-3 hp:has-[>[data-align=block-start]]:[&>input]:pb-3 hp:has-[>[data-align=inline-end]]:[&>input]:pr-1.5 hp:has-[>[data-align=inline-start]]:[&>input]:pl-1.5 hp:relative hp:flex hp:w-full hp:min-w-0 hp:items-center hp:outline-none hp:has-[>textarea]:h-auto",
		className
	)}
	{...props}
>
	{@render children?.()}
</div>

// packages/vue/src/ui/input-group/InputGroup.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { cn } from '../../lib/utils'

const props = defineProps<{ class?: HTMLAttributes['class'] }>()
</script>

<template>
  <div
    data-slot="input-group"
    role="group"
    :class="cn(
      'hp:group/input-group hp:relative hp:flex hp:h-9 hp:w-full hp:min-w-0 hp:items-center hp:rounded-md hp:border hp:border-input hp:shadow-xs hp:outline-none hp:transition-[color,box-shadow] hp:has-[>textarea]:h-auto hp:dark:bg-input/30',
      'hp:has-[>[data-align=inline-start]]:[&>input]:ps-2 hp:has-[>[data-align=inline-end]]:[&>input]:pe-2',
      'hp:has-[>[data-align=block-start]]:h-auto hp:has-[>[data-align=block-start]]:flex-col hp:has-[>[data-align=block-start]]:[&>input]:pb-3',
      'hp:has-[>[data-align=block-end]]:h-auto hp:has-[>[data-align=block-end]]:flex-col hp:has-[>[data-align=block-end]]:[&>input]:pt-3',
      'hp:has-[[data-slot=input-group-control]:focus-visible]:border-ring hp:has-[[data-slot=input-group-control]:focus-visible]:ring-3 hp:has-[[data-slot=input-group-control]:focus-visible]:ring-ring/50',
      'hp:has-[[data-slot][aria-invalid=true]]:border-destructive hp:has-[[data-slot][aria-invalid=true]]:ring-destructive/20 hp:dark:has-[[data-slot][aria-invalid=true]]:ring-destructive/40',
      props.class,
    )"
  ><slot /></div>
</template>
