// packages/vue/src/ui/card/CardDescription.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <p
    data-slot="card-description"
    :class="cn('hp:text-muted-foreground hp:text-sm', props.class)"
  >
    <slot />
  </p>
</template>

// packages/svelte/src/ui/card/card-description.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "../../lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLParagraphElement>> = $props();
</script>

<p
	bind:this={ref}
	data-slot="card-description"
	class={cn("hp:text-sm hp:text-muted-foreground", className)}
	{...restProps}
>
	{@render children?.()}
</p>
