// apps/example-nuxt/app/pages/admin/profile/mfa/recovery-codes.vue
<!-- @holo-panels-managed sha256:90c3eb5400971febf3e65c7c3d97f8cbd8eed906f0ea272428b526d19c99a3a0 -->
<script setup lang="ts">
import { PanelMultiFactorPage } from '@holo-js/panels-nuxt'

const brandName = "Holo Panels Admin"
const themeColors = {"primary":"#7c3aed"}
</script>

<template>
  <PanelMultiFactorPage :brand-name="brandName" panel-id="admin" simple-page-max-content-width="lg" theme="system" :theme-colors="themeColors" />
</template>

// apps/example-sveltekit/src/routes/admin/profile/mfa/recovery-codes/+page.svelte
<!-- @holo-panels-managed sha256:1d2e50a79ef53823325c5ebda06cc9f48bd86ccdbd132490235d71ff98f02e8a -->
<script lang="ts">
  import '@holo-js/panels-svelte/style.css'
  import { PanelMultiFactorPage } from '@holo-js/panels-sveltekit'
</script>

<PanelMultiFactorPage brandName={"Holo Panels"} panelId="admin" simplePageMaxContentWidth="lg" theme="system" themeColors={{"primary":"#7c3aed"}} />
