// apps/example-next/app/admin/profile/mfa/recovery-codes/page.tsx
// @holo-panels-managed sha256:540adc32f9485d0eddb1f55a5c4cc912f0afbe6778c2399fa0b0e39c99a4d719
'use client'

import '@holo-js/panels-react/style.css'
import { NextPanelMultiFactorPage } from '@holo-js/panels-next/client'

export default function AuthPage() {
  return <NextPanelMultiFactorPage brandName={"Holo Panels Admin"} panelId="admin" simplePageMaxContentWidth="lg" theme="system" themeColors={{"primary":"#7c3aed"}} />
}

// apps/example-sveltekit/src/routes/admin/profile/mfa/recovery-codes/+page.svelte
<!-- @holo-panels-managed sha256:1d2e50a79ef53823325c5ebda06cc9f48bd86ccdbd132490235d71ff98f02e8a -->
<script lang="ts">
  import '@holo-js/panels-svelte/style.css'
  import { PanelMultiFactorPage } from '@holo-js/panels-sveltekit'
</script>

<PanelMultiFactorPage brandName={"Holo Panels"} panelId="admin" simplePageMaxContentWidth="lg" theme="system" themeColors={{"primary":"#7c3aed"}} />
