// apps/example-sveltekit/src/routes/admin/login/+page.svelte
<!-- @holo-panels-managed sha256:8c46f5e02eef26d3acae624de3dc8b82c95ddaf1717c6ec7edfd3657a35ccce1 -->
<script lang="ts">
  import '@holo-js/panels-svelte/style.css'
  import { PanelLoginPage } from '@holo-js/panels-sveltekit'
</script>

<PanelLoginPage brandName={"Holo Panels"} panelId="admin" simplePageMaxContentWidth="lg" theme="system" appearance={{"colors":{"primary":"#7c3aed"},"density":"comfortable","fontFamily":null,"monoFontFamily":null,"serifFontFamily":null,"tokens":{}}} />

// apps/example-next/app/admin/login/page.tsx
// @holo-panels-managed sha256:eaf2870ee8f7b71413e253bcb2fb98139bd3a13ce2845ab2e6ca611ec50614bf
'use client'

import '@holo-js/panels-react/style.css'
import { NextPanelLoginPage } from '@holo-js/panels-next/client'

export default function LoginPage() {
  return <NextPanelLoginPage brandName={"Holo Panels Admin"} panelId="admin" simplePageMaxContentWidth="lg" theme="system" appearance={{"colors":{"primary":"#7c3aed"},"density":"comfortable","fontFamily":null,"monoFontFamily":null,"serifFontFamily":null,"tokens":{}}} />
}
