// packages/vue/src/ui/select/SelectScrollUpButton.vue
<script setup lang="ts">
import type { SelectScrollUpButtonProps } from "reka-ui"
import type { HTMLAttributes } from "vue"
import { ChevronUpIcon } from '@radix-icons/vue'
import { reactiveOmit } from "@vueuse/core"
import { SelectScrollUpButton, useForwardProps } from "reka-ui"
import { cn } from "@/lib/utils"

const props = defineProps<SelectScrollUpButtonProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = reactiveOmit(props, "class")

const forwardedProps = useForwardProps(delegatedProps)
</script>

<template>
  <SelectScrollUpButton
    data-slot="select-scroll-up-button"
    v-bind="forwardedProps"
    :class="cn('hp:flex hp:cursor-default hp:items-center hp:justify-center hp:py-1', props.class)"
  >
    <slot>
      <ChevronUpIcon class="hp:size-4" />
    </slot>
  </SelectScrollUpButton>
</template>

// packages/svelte/src/ui/select/select-scroll-up-button.svelte
<script lang="ts">
	import { Select as SelectPrimitive } from "bits-ui";
	import ChevronUpIcon from '@lucide/svelte/icons/chevron-up';
	import { cn, type WithoutChildrenOrChild } from "../../lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: WithoutChildrenOrChild<SelectPrimitive.ScrollUpButtonProps> = $props();
</script>

<SelectPrimitive.ScrollUpButton
	bind:ref
	data-slot="select-scroll-up-button"
	class={cn("hp:z-10 hp:flex hp:cursor-default hp:items-center hp:justify-center hp:bg-popover hp:py-1 hp:[&_svg:not([class*='size-'])]:size-4 hp:top-0 hp:w-full", className)}
	{...restProps}
>
	<ChevronUpIcon  />
</SelectPrimitive.ScrollUpButton>
