// packages/vue/src/ui/select/SelectSeparator.vue
<script setup lang="ts">
import type { SelectSeparatorProps } from "reka-ui"
import type { HTMLAttributes } from "vue"
import { reactiveOmit } from "@vueuse/core"
import { SelectSeparator } from "reka-ui"
import { cn } from "@/lib/utils"

const props = defineProps<SelectSeparatorProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = reactiveOmit(props, "class")
</script>

<template>
  <SelectSeparator
    data-slot="select-separator"
    v-bind="delegatedProps"
    :class="cn('hp:bg-border hp:pointer-events-none hp:-mx-1 hp:my-1 hp:h-px', props.class)"
  />
</template>

// packages/svelte/src/ui/select/select-separator.svelte
<script lang="ts">
	import { Separator } from "../separator/index.js";
	import { cn } from "../../lib/utils.js";
	import type { Separator as SeparatorPrimitive } from "bits-ui";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: SeparatorPrimitive.RootProps = $props();
</script>

<Separator
	bind:ref
	data-slot="select-separator"
	class={cn("hp:-mx-1 hp:my-1 hp:h-px hp:bg-border hp:pointer-events-none", className)}
	{...restProps}
/>
