// packages/vue/src/ui/native-select/NativeSelectOption.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{ class?: HTMLAttributes["class"] }>()
</script>

<template>
  <option data-slot="native-select-option" :class="cn('hp:bg-popover hp:text-popover-foreground', props.class)">
    <slot />
  </option>
</template>

// packages/svelte/src/ui/native-select/native-select-option.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "../../lib/utils.js";
	import type { HTMLOptionAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLOptionAttributes> = $props();
</script>

<option
	bind:this={ref}
	data-slot="native-select-option"
	class={cn("hp:bg-[Canvas] hp:text-[CanvasText]", className)}
	{...restProps}
>
	{@render children?.()}
</option>
