// packages/vue/src/ui/native-select/NativeSelectOptGroup.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{ class?: HTMLAttributes["class"] }>()
</script>

<template>
  <optgroup data-slot="native-select-optgroup" :class="cn('hp:bg-popover hp:text-popover-foreground', props.class)">
    <slot />
  </optgroup>
</template>

// packages/svelte/src/ui/native-select/native-select-opt-group.svelte
<script lang="ts">
	import type { WithElementRef } from "../../lib/utils.js";
	import type { HTMLOptgroupAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		children,
		...restProps
	}: WithElementRef<HTMLOptgroupAttributes> = $props();
</script>

<optgroup bind:this={ref} data-slot="native-select-opt-group" {...restProps}>
	{@render children?.()}
</optgroup>
