// packages/react/src/ui/native-select.tsx
import * as React from "react"
import { ChevronDownIcon } from "lucide-react"

import { cn } from "../lib/utils"

function NativeSelect({
  className,
  size = "default",
  ...props
}: Omit<React.ComponentProps<"select">, "size"> & { size?: "sm" | "default" }) {
  return (
    <div
      className="hp:group/native-select hp:relative hp:w-full hp:has-[select:disabled]:opacity-50"
      data-slot="native-select-wrapper"
    >
      <select
        data-slot="native-select"
        data-size={size}
        className={cn(
          "hp:h-9 hp:w-full hp:min-w-0 hp:appearance-none hp:rounded-md hp:border hp:border-input hp:bg-transparent hp:px-3 hp:py-2 hp:pe-9 hp:text-sm hp:shadow-xs hp:transition-[color,box-shadow] hp:outline-none hp:selection:bg-primary hp:selection:text-primary-foreground hp:placeholder:text-muted-foreground hp:disabled:pointer-events-none hp:disabled:cursor-not-allowed hp:data-[size=sm]:h-8 hp:data-[size=sm]:py-1 hp:dark:bg-input/30 hp:dark:hover:bg-input/50",
          "hp:focus-visible:border-ring hp:focus-visible:ring-[3px] hp:focus-visible:ring-ring/50",
          "hp:aria-invalid:border-destructive hp:aria-invalid:ring-destructive/20 hp:dark:aria-invalid:ring-destructive/40",
          className
        )}
        {...props}
      />
      <ChevronDownIcon
        className="hp:pointer-events-none hp:absolute hp:top-1/2 hp:right-3.5 hp:size-4 hp:-translate-y-1/2 hp:text-muted-foreground hp:opacity-50 hp:select-none"
        aria-hidden="true"
        data-slot="native-select-icon"
      />
    </div>
  )
}

function NativeSelectOption({
  className,
  ...props
}: React.ComponentProps<"option">) {
  return (
    <option
      data-slot="native-select-option"
      className={cn("hp:bg-[Canvas] hp:text-[CanvasText]", className)}
      {...props}
    />
  )
}

function NativeSelectOptGroup({
  className,
  ...props
}: React.ComponentProps<"optgroup">) {
  return (
    <optgroup
      data-slot="native-select-optgroup"
      className={cn("hp:bg-[Canvas] hp:text-[CanvasText]", className)}
      {...props}
    />
  )
}

export { NativeSelect, NativeSelectOptGroup, NativeSelectOption }

// packages/svelte/src/ui/native-select/native-select.svelte
<script lang="ts">
	import ChevronDownIcon from '@lucide/svelte/icons/chevron-down';
	import { cn, type WithElementRef } from "../../lib/utils.js";
	import type { HTMLSelectAttributes } from "svelte/elements";

	type NativeSelectProps = Omit<WithElementRef<HTMLSelectAttributes>, "size"> & {
		size?: "sm" | "default";
	};

	let {
		ref = $bindable(null),
		value = $bindable(),
		class: className,
		size = "default",
		children,
		...restProps
	}: NativeSelectProps = $props();
</script>

<div
	class={cn(
		"hp:cn-native-select-wrapper hp:group/native-select hp:relative hp:w-full hp:has-[select:disabled]:opacity-50",
		className
	)}
	data-slot="native-select-wrapper"
	data-size={size}
>
	<select
		bind:value
		bind:this={ref}
		data-slot="native-select"
		data-size={size}
		class="hp:h-8 hp:w-full hp:min-w-0 hp:appearance-none hp:rounded-lg hp:border hp:border-input hp:bg-transparent hp:py-1 hp:pr-8 hp:pl-2.5 hp:text-sm hp:transition-colors hp:select-none hp:selection:bg-primary hp:selection:text-primary-foreground hp:placeholder:text-muted-foreground hp:focus-visible:border-ring hp:focus-visible:ring-3 hp:focus-visible:ring-ring/50 hp:aria-invalid:border-destructive hp:aria-invalid:ring-3 hp:aria-invalid:ring-destructive/20 hp:data-[size=sm]:h-7 hp:data-[size=sm]:rounded-[min(var(--radius-md),10px)] hp:data-[size=sm]:py-0.5 hp:dark:bg-input/30 hp:dark:hover:bg-input/50 hp:dark:aria-invalid:border-destructive/50 hp:dark:aria-invalid:ring-destructive/40 hp:outline-none hp:disabled:pointer-events-none hp:disabled:cursor-not-allowed"
		{...restProps}
	>
		{@render children?.()}
	</select>
	<ChevronDownIcon class="hp:top-1/2 hp:right-2.5 hp:size-4 hp:-translate-y-1/2 hp:text-muted-foreground hp:pointer-events-none hp:absolute hp:select-none" aria-hidden data-slot="native-select-icon" />
</div>
