// packages/svelte/src/ui/empty/empty-title.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "../../lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();
</script>

<div
	bind:this={ref}
	data-slot="empty-title"
	class={cn("hp:text-sm hp:font-medium hp:tracking-tight", className)}
	{...restProps}
>
	{@render children?.()}
</div>

// packages/vue/src/ui/empty/EmptyTitle.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <div
    data-slot="empty-title"
    :class="cn('hp:text-lg hp:font-medium hp:tracking-tight', props.class)"
  >
    <slot />
  </div>
</template>
