// packages/vue/src/ui/table/TableCaption.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <caption
    data-slot="table-caption"
    :class="cn('hp:text-muted-foreground hp:mt-4 hp:text-sm', props.class)"
  >
    <slot />
  </caption>
</template>

// packages/svelte/src/ui/table/table-caption.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "../../lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLElement>> = $props();
</script>

<caption
	bind:this={ref}
	data-slot="table-caption"
	class={cn("hp:mt-4 hp:text-sm hp:text-muted-foreground", className)}
	{...restProps}
>
	{@render children?.()}
</caption>
