// packages/vue/src/ui/table/Table.vue
<script setup lang="ts">
import { type HTMLAttributes } from 'vue'
import { cn } from '@/lib/utils'

const props = defineProps<{
  class?: HTMLAttributes['class']
  readonly containerProps?: HTMLAttributes
}>()

defineOptions({
  inheritAttrs: false,
})
</script>

<template>
  <div v-bind="props.containerProps" data-slot="table-container" :class="cn('hp:relative hp:w-full hp:overflow-x-auto', props.containerProps?.class)">
    <table v-bind="$attrs" data-slot="table" :class="cn('hp:w-full hp:caption-bottom hp:text-sm', props.class)">
      <slot />
    </table>
  </div>
</template>

// packages/svelte/src/ui/table/table.svelte
<script lang="ts">
	import { cn, type WithElementRef } from '../../lib/utils.js'
	import { type HTMLAttributes, type HTMLTableAttributes } from 'svelte/elements'

	let {
		ref = $bindable(null),
		class: className,
		containerProps,
		children,
		...restProps
	}: WithElementRef<HTMLTableAttributes> & { readonly containerProps?: HTMLAttributes<HTMLDivElement> } = $props()
</script>

<div {...containerProps} data-slot="table-container" class={cn('hp:relative hp:w-full hp:overflow-x-auto', containerProps?.class)}>
	<table bind:this={ref} data-slot="table" class={cn("hp:w-full hp:caption-bottom hp:text-sm", className)} {...restProps}>
		{@render children?.()}
	</table>
</div>
