// packages/vue/src/ui/table/TableRow.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <tr
    data-slot="table-row"
    :class="cn('hp:hover:bg-muted/50 hp:data-[state=selected]:bg-muted hp:border-b hp:transition-colors', props.class)"
  >
    <slot />
  </tr>
</template>

// packages/svelte/src/ui/table/table-row.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "../../lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLTableRowElement>> = $props();
</script>

<tr bind:this={ref} data-slot="table-row" class={cn("hp:border-b hp:transition-colors hp:hover:bg-muted/50 hp:data-[state=selected]:bg-muted", className)} {...restProps}>
	{@render children?.()}
</tr>
