// packages/svelte/src/ui/alert/alert-description.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "../../lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();
</script>

<div
	bind:this={ref}
	data-slot="alert-description"
	class={cn(
		"hp:text-sm hp:text-balance hp:text-muted-foreground hp:md:text-pretty hp:[&_p:not(:last-child)]:mb-4 hp:[&_a]:underline hp:[&_a]:underline-offset-3 hp:[&_a]:hover:text-foreground",
		className
	)}
	{...restProps}
>
	{@render children?.()}
</div>

// packages/vue/src/ui/alert/AlertDescription.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <div
    data-slot="alert-description"
    :class="cn('hp:text-muted-foreground hp:col-start-2 hp:text-sm hp:[&_p]:leading-relaxed', props.class)"
  >
    <slot />
  </div>
</template>
