// packages/svelte/src/ui/alert/alert-title.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "../../lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();
</script>

<div
	bind:this={ref}
	data-slot="alert-title"
	class={cn(
		"hp:font-medium hp:group-has-[>svg]/alert:col-start-2 hp:[&_a]:underline hp:[&_a]:underline-offset-3 hp:[&_a]:hover:text-foreground",
		className
	)}
	{...restProps}
>
	{@render children?.()}
</div>

// packages/vue/src/ui/alert/AlertTitle.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <div
    data-slot="alert-title"
    :class="cn('hp:col-start-2 hp:line-clamp-1 hp:min-h-4 hp:font-medium hp:tracking-tight', props.class)"
  >
    <slot />
  </div>
</template>
