// apps/example-next/app/blog/[slug]/page.tsx
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { createExampleBlogDomain } from '../../../server/domain/blog'

interface BlogPostProps {
  readonly params: Promise<{ readonly slug: string }>
}

export default async function BlogPost({ params }: BlogPostProps) {
  const { slug } = await params
  const post = createExampleBlogDomain().findPublishedPost('tenant-acme', slug)
  if (!post) notFound()

  return (
    <main style={{ fontFamily: 'sans-serif', margin: '0 auto', maxWidth: '48rem', padding: '3rem 1.5rem' }}>
      <p><Link href="/blog">Back to all posts</Link></p>
      <article>
        <p>{post.category.name} · {post.tags.map(tag => tag.name).join(', ')}</p>
        <h1>{post.title}</h1>
        {post.media ? <img alt={post.media.alt} height="360" src={post.media.url} width="640" /> : null}
        <p>{post.body}</p>
      </article>
      <section aria-labelledby="comments-heading">
        <h2 id="comments-heading">Comments</h2>
        {post.comments.length === 0 ? <p>No approved comments yet.</p> : post.comments.map(comment => (
          <blockquote key={comment.id}>
            <p>{comment.body}</p>
            <footer>— {comment.authorName}</footer>
          </blockquote>
        ))}
      </section>
    </main>
  )
}

// apps/example-nuxt/app/pages/blog/[slug].vue
<script setup lang="ts">
import { getExampleBlogPost } from '../../../server/blog'

const route = useRoute()
const tenant = typeof route.query.tenant === 'string' ? route.query.tenant : null
const slug = typeof route.params.slug === 'string' ? route.params.slug : ''
const entry = computed(() => getExampleBlogPost(slug, { tenant }))

if (!entry.value) throw createError({ statusCode: 404, statusMessage: 'Post not found' })
</script>

<template>
  <main v-if="entry">
    <NuxtLink :to="{ path: '/blog', query: { tenant: entry.tenant.routeKey } }">Back to {{ entry.tenant.name }} journal</NuxtLink>
    <article>
      <p>{{ entry.post.category?.name }} · {{ entry.post.tags.map(tag => tag.name).join(', ') }}</p>
      <h1>{{ entry.post.title }}</h1>
      <p>{{ entry.post.body }}</p>
      <p v-if="entry.post.media?.private">Private media is available only inside the authorized panel.</p>
    </article>
    <section aria-labelledby="comments-heading">
      <h2 id="comments-heading">Comments</h2>
      <p v-if="entry.comments.length === 0">No approved comments yet.</p>
      <article v-for="comment in entry.comments" :key="comment.id">
        <h3>{{ comment.authorName }}</h3>
        <p>{{ comment.body }}</p>
      </article>
    </section>
  </main>
</template>

<style scoped>
main { margin: 0 auto; max-width: 48rem; padding: 3rem 1.5rem; font-family: sans-serif; }
article { margin-block: 2rem; }
</style>
