// packages/svelte/src/ui/avatar/avatar-image.svelte
<script lang="ts">
	import { Avatar as AvatarPrimitive } from "bits-ui";
	import { cn } from "../../lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: AvatarPrimitive.ImageProps = $props();
</script>

<AvatarPrimitive.Image
	bind:ref
	data-slot="avatar-image"
	class={cn("hp:rounded-full hp:aspect-square hp:size-full hp:object-cover", className)}
	{...restProps}
/>

// packages/vue/src/ui/avatar/AvatarImage.vue
<script setup lang="ts">
import type { AvatarImageProps } from "reka-ui"
import { AvatarImage } from "reka-ui"

const props = defineProps<AvatarImageProps>()
</script>

<template>
  <AvatarImage
    data-slot="avatar-image"
    v-bind="props"
    class="hp:aspect-square hp:size-full"
  >
    <slot />
  </AvatarImage>
</template>
