// packages/svelte/src/ui/avatar/avatar-fallback.svelte
<script lang="ts">
	import { Avatar as AvatarPrimitive } from "bits-ui";
	import { cn } from "../../lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: AvatarPrimitive.FallbackProps = $props();
</script>

<AvatarPrimitive.Fallback
	bind:ref
	data-slot="avatar-fallback"
	class={cn(
		"hp:rounded-full hp:bg-muted hp:text-muted-foreground hp:flex hp:size-full hp:items-center hp:justify-center hp:text-sm hp:group-data-[size=sm]/avatar:text-xs",
		className
	)}
	{...restProps}
/>

// packages/vue/src/ui/avatar/AvatarFallback.vue
<script setup lang="ts">
import type { AvatarFallbackProps } from "reka-ui"
import type { HTMLAttributes } from "vue"
import { reactiveOmit } from "@vueuse/core"
import { AvatarFallback } from "reka-ui"
import { cn } from "@/lib/utils"

const props = defineProps<AvatarFallbackProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = reactiveOmit(props, "class")
</script>

<template>
  <AvatarFallback
    data-slot="avatar-fallback"
    v-bind="delegatedProps"
    :class="cn('hp:bg-muted hp:flex hp:size-full hp:items-center hp:justify-center hp:rounded-full', props.class)"
  >
    <slot />
  </AvatarFallback>
</template>
