// packages/react/src/widgets/dashboard-filters.tsx
import { usePanelTranslator } from '../localization'
import { useSyncExternalStore, type ReactNode } from 'react'
import { actionFormField, type DashboardFilterStore } from '@holo-js/panels-client'
import { Button } from '../internal-ui'
import { ReactSchemaRenderer } from '../schema/renderer'
import { ReactFieldRenderer } from '../fields/renderer'
import type { ComponentRegistry } from '../registry'

export function ReactDashboardFilters({ store, panelId, registry }: { readonly store: DashboardFilterStore, readonly panelId: string, readonly registry: ComponentRegistry }): ReactNode {
  const translate = usePanelTranslator()
  const state = useSyncExternalStore(listener => store.form.subscribe(listener), () => store.form.state, () => store.form.state)
  return <form aria-label={translate('widgets.dashboardFilters')} className="hp-dashboard-filters hp:grid hp:gap-4" noValidate onSubmit={event => { event.preventDefault(); void store.submit() }}>
    <ReactSchemaRenderer panelId={panelId} registry={registry} schema={store.schema} renderContent={({ component }) => {
      const definition = actionFormField(component)
      return definition ? <ReactFieldRenderer definition={definition} optionStore={store.optionStore(definition)} panelId={panelId} registry={registry} store={store.form} /> : null
    }} />
    <div className="hp:flex hp:gap-2"><Button disabled={state.submitting} type="submit">{translate('tables.applyFilters')}</Button><Button disabled={state.submitting} onClick={() => void store.submit(true)} type="button" variant="outline">{translate('tables.resetFilters')}</Button></div>
    {state.errors._root?.map(message => <p key={message} role="alert">{message}</p>)}
  </form>
}

// packages/svelte/src/widgets/DashboardFilters.svelte
<script lang="ts">
  import { usePanelTranslator } from '../localization'
  const translate = usePanelTranslator()
  import { actionFormField, type DashboardFilterStore } from '@holo-js/panels-client'
  import { Button } from '../ui/button'
  import { type SvelteComponentRegistry } from '../registry'
  import { toSvelteState } from '../stores'
  import SchemaRenderer from '../schemas/SchemaRenderer.svelte'
  import FieldRenderer from '../fields/FieldRenderer.svelte'

  let { store, panelId, registry }: { readonly store: DashboardFilterStore, readonly panelId: string, readonly registry: SvelteComponentRegistry } = $props()
  const filterState = $derived.by(() => toSvelteState(store.form))
</script>

<form aria-label={translate('widgets.dashboardFilters')} class="hp-dashboard-filters hp:grid hp:gap-4" novalidate onsubmit={event => { event.preventDefault(); void store.submit() }}>
  <SchemaRenderer {panelId} {registry} schema={store.schema}>
    {#snippet renderContent({ component })}
      {@const definition = actionFormField(component)}
      {#if definition}<FieldRenderer definition={{ ...definition, helperText: definition.helperText ?? undefined, hint: definition.hint ?? undefined, placeholder: definition.placeholder ?? undefined }} form={store.form} optionStore={store.optionStore(definition)} {panelId} {registry} />{/if}
    {/snippet}
  </SchemaRenderer>
  <div class="hp:flex hp:gap-2"><Button disabled={$filterState.submitting} type="submit">{translate('tables.applyFilters')}</Button><Button disabled={$filterState.submitting} onclick={() => void store.submit(true)} type="button" variant="outline">{translate('tables.resetFilters')}</Button></div>
  {#each $filterState.errors._root ?? [] as message}<p role="alert">{message}</p>{/each}
</form>
