// packages/vue/src/ui/pagination/PaginationEllipsis.vue
<script setup lang="ts">
import type { PaginationEllipsisProps } from "reka-ui"
import type { HTMLAttributes } from "vue"
import { DotsHorizontalIcon } from '@radix-icons/vue'
import { reactiveOmit } from "@vueuse/core"
import { PaginationEllipsis } from "reka-ui"
import { cn } from "@/lib/utils"

const props = defineProps<PaginationEllipsisProps & { class?: HTMLAttributes["class"] }>()

const delegatedProps = reactiveOmit(props, "class")
</script>

<template>
  <PaginationEllipsis
    data-slot="pagination-ellipsis"
    v-bind="delegatedProps"
    :class="cn('hp:flex hp:size-9 hp:items-center hp:justify-center', props.class)"
  >
    <slot>
      <DotsHorizontalIcon class="hp:size-4" />
      <span class="hp:sr-only">More pages</span>
    </slot>
  </PaginationEllipsis>
</template>

// packages/svelte/src/ui/pagination/pagination-ellipsis.svelte
<script lang="ts">
	import MoreHorizontalIcon from '@lucide/svelte/icons/more-horizontal';
	import { cn, type WithElementRef, type WithoutChildren } from "../../lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: WithoutChildren<WithElementRef<HTMLAttributes<HTMLSpanElement>>> = $props();
</script>

<span
	bind:this={ref}
	aria-hidden="true"
	data-slot="pagination-ellipsis"
	class={cn("hp:size-8 hp:items-center hp:justify-center hp:[&_svg:not([class*='size-'])]:size-4 hp:flex hp:items-center hp:justify-center", className)}
	{...restProps}
>
	<MoreHorizontalIcon  />
	<span class="hp:sr-only">More pages</span>
</span>
