// packages/svelte/src/ui/sheet/sheet-header.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "../../lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();
</script>

<div
	bind:this={ref}
	data-slot="sheet-header"
	class={cn("hp:gap-0.5 hp:p-4 hp:flex hp:flex-col", className)}
	{...restProps}
>
	{@render children?.()}
</div>

// packages/vue/src/ui/sheet/SheetHeader.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{ class?: HTMLAttributes["class"] }>()
</script>

<template>
  <div
    data-slot="sheet-header"
    :class="cn('hp:flex hp:flex-col hp:gap-1.5 hp:p-4', props.class)"
  >
    <slot />
  </div>
</template>
