// packages/svelte/src/ui/sheet/sheet-content.svelte
<script lang="ts" module>
	export type Side = "top" | "right" | "bottom" | "left";
</script>

<script lang="ts">
	import { Dialog as SheetPrimitive } from "bits-ui";
	import XIcon from '@lucide/svelte/icons/x';
	import { Button } from "../button/index.js";
	import { cn, type WithoutChildrenOrChild } from "../../lib/utils.js";
	import SheetOverlay from "./sheet-overlay.svelte";
	import SheetPortal from "./sheet-portal.svelte";
	import type { Snippet } from "svelte";
	import type { ComponentProps } from "svelte";

	let {
		ref = $bindable(null),
		class: className,
		side = "right",
		showCloseButton = true,
		portalProps,
		children,
		...restProps
	}: WithoutChildrenOrChild<SheetPrimitive.ContentProps> & {
		portalProps?: WithoutChildrenOrChild<ComponentProps<typeof SheetPortal>>;
		side?: Side;
		showCloseButton?: boolean;
		children: Snippet;
	} = $props();
</script>

<SheetPortal {...portalProps}>
	<SheetOverlay />
	<SheetPrimitive.Content
		bind:ref
		data-slot="sheet-content"
		data-panels-component="slide-over"
		data-side={side}
		class={cn(
			"hp:fixed hp:z-50 hp:flex hp:flex-col hp:gap-4 hp:bg-popover hp:bg-clip-padding hp:text-sm hp:text-popover-foreground hp:shadow-lg hp:transition hp:duration-200 hp:ease-in-out hp:data-[side=bottom]:inset-x-0 hp:data-[side=bottom]:bottom-0 hp:data-[side=bottom]:h-auto hp:data-[side=bottom]:border-t hp:data-[side=left]:inset-y-0 hp:data-[side=left]:left-0 hp:data-[side=left]:h-full hp:data-[side=left]:w-3/4 hp:data-[side=left]:border-r hp:data-[side=right]:inset-y-0 hp:data-[side=right]:right-0 hp:data-[side=right]:h-full hp:data-[side=right]:w-3/4 hp:data-[side=right]:border-l hp:data-[side=top]:inset-x-0 hp:data-[side=top]:top-0 hp:data-[side=top]:h-auto hp:data-[side=top]:border-b hp:data-[side=left]:sm:max-w-sm hp:data-[side=right]:sm:max-w-sm hp:data-[state=open]:animate-in hp:data-[state=open]:fade-in-0 hp:data-[side=bottom]:data-[state=open]:slide-in-from-bottom-10 hp:data-[side=left]:data-[state=open]:slide-in-from-left-10 hp:data-[side=right]:data-[state=open]:slide-in-from-right-10 hp:data-[side=top]:data-[state=open]:slide-in-from-top-10 hp:data-[state=closed]:animate-out hp:data-[state=closed]:fade-out-0 hp:data-[side=bottom]:data-[state=closed]:slide-out-to-bottom-10 hp:data-[side=left]:data-[state=closed]:slide-out-to-left-10 hp:data-[side=right]:data-[state=closed]:slide-out-to-right-10 hp:data-[side=top]:data-[state=closed]:slide-out-to-top-10",
			"hp-slide-over",
			className
		)}
		{...restProps}
	>
		{@render children?.()}
		{#if showCloseButton}
			<SheetPrimitive.Close data-slot="sheet-close">
				{#snippet child({ props })}
					<Button variant="ghost" class="hp:absolute hp:top-3 hp:end-3" size="icon-sm" {...props}>
						<XIcon  />
						<span class="hp:sr-only hp:rtl:hidden">Close</span><span class="hp:sr-only hp:hidden hp:rtl:inline">إغلاق</span>
					</Button>
				{/snippet}
			</SheetPrimitive.Close>
		{/if}
	</SheetPrimitive.Content>
</SheetPortal>

// packages/vue/src/ui/sheet/SheetContent.vue
<script setup lang="ts">
import type { DialogContentEmits, DialogContentProps } from "reka-ui"
import type { HTMLAttributes } from "vue"
import { Cross2Icon } from '@radix-icons/vue'
import { reactiveOmit } from "@vueuse/core"
import {
  DialogClose,
  DialogContent,
  DialogPortal,
  useForwardPropsEmits,
} from "reka-ui"
import { cn } from "@/lib/utils"
import SheetOverlay from "./SheetOverlay.vue"

interface SheetContentProps extends DialogContentProps {
  class?: HTMLAttributes["class"]
  side?: "top" | "right" | "bottom" | "left"
}

defineOptions({
  inheritAttrs: false,
})

const props = withDefaults(defineProps<SheetContentProps>(), {
  side: "right",
})
const emits = defineEmits<DialogContentEmits>()

const delegatedProps = reactiveOmit(props, "class", "side")

const forwarded = useForwardPropsEmits(delegatedProps, emits)
</script>

<template>
  <DialogPortal>
    <SheetOverlay />
    <DialogContent
      :data-side="side"
      data-slot="sheet-content"
      data-panels-component="slide-over"
      :class="cn(
        'hp:bg-background hp:data-[state=open]:animate-in hp:data-[state=closed]:animate-out hp:fixed hp:z-50 hp:flex hp:flex-col hp:gap-4 hp:shadow-lg hp:transition hp:duration-200 hp:ease-in-out',
        side === 'right'
          && 'hp:data-[state=closed]:slide-out-to-right hp:data-[state=open]:slide-in-from-right hp:inset-y-0 hp:right-0 hp:h-full hp:w-3/4 hp:border-l hp:sm:max-w-sm',
        side === 'left'
          && 'hp:data-[state=closed]:slide-out-to-left hp:data-[state=open]:slide-in-from-left hp:inset-y-0 hp:left-0 hp:h-full hp:w-3/4 hp:border-r hp:sm:max-w-sm',
        side === 'top'
          && 'hp:data-[state=closed]:slide-out-to-top hp:data-[state=open]:slide-in-from-top hp:inset-x-0 hp:top-0 hp:h-auto hp:border-b',
        side === 'bottom'
          && 'hp:data-[state=closed]:slide-out-to-bottom hp:data-[state=open]:slide-in-from-bottom hp:inset-x-0 hp:bottom-0 hp:h-auto hp:border-t',
        'hp-slide-over',
        props.class)"
      v-bind="{ ...$attrs, ...forwarded }"
    >
      <slot />

      <DialogClose
        class="hp:ring-offset-background hp:focus:ring-ring hp:data-[state=open]:bg-secondary hp:absolute hp:top-4 hp:end-4 hp:rounded-xs hp:opacity-70 hp:transition-opacity hp:hover:opacity-100 hp:focus:ring-2 hp:focus:ring-offset-2 hp:focus:outline-hidden hp:disabled:pointer-events-none"
      >
        <Cross2Icon class="hp:size-4" />
        <span class="hp:sr-only hp:rtl:hidden">Close</span><span class="hp:sr-only hp:hidden hp:rtl:inline">إغلاق</span>
      </DialogClose>
    </DialogContent>
  </DialogPortal>
</template>
